import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from "docx";
import { saveAs } from "file-saver";

function formatDate(): string {
  return new Date().toLocaleDateString("en-IN", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });
}

function parseContentToDocx(content: string): Paragraph[] {
  const lines = content.split("\n");
  const paragraphs: Paragraph[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (!trimmed) {
      paragraphs.push(new Paragraph({ spacing: { after: 120 } }));
      continue;
    }

    if (/^#{1,3}\s/.test(trimmed)) {
      const text = trimmed.replace(/^#{1,3}\s/, "");
      paragraphs.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_1,
          children: [new TextRun({ text, bold: true, size: 28 })],
          spacing: { before: 240, after: 120 },
        }),
      );
      continue;
    }

    if (/^\*\*(.+)\*\*$/.test(trimmed)) {
      const text = trimmed.replace(/^\*\*(.+)\*\*$/, "$1");
      paragraphs.push(
        new Paragraph({
          children: [new TextRun({ text, bold: true, size: 24 })],
          spacing: { before: 120, after: 60 },
        }),
      );
      continue;
    }

    paragraphs.push(
      new Paragraph({
        children: [new TextRun({ text: trimmed, size: 24 })],
        spacing: { after: 80 },
      }),
    );
  }

  return paragraphs;
}

export async function exportAsWord(
  content: string,
  title: string,
): Promise<void> {
  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
          },
        },
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: "LAWBITE",
                bold: true,
                size: 20,
                color: "888888",
              }),
            ],
            alignment: AlignmentType.RIGHT,
            spacing: { after: 60 },
          }),
          new Paragraph({
            children: [
              new TextRun({ text: formatDate(), size: 20, color: "888888" }),
            ],
            alignment: AlignmentType.RIGHT,
            spacing: { after: 200 },
          }),
          new Paragraph({
            children: [new TextRun({ text: title, bold: true, size: 32 })],
            heading: HeadingLevel.TITLE,
            spacing: { after: 200 },
          }),
          new Paragraph({
            border: {
              bottom: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
            },
            spacing: { after: 200 },
          }),
          ...parseContentToDocx(content),
          new Paragraph({ spacing: { after: 400 } }),
          new Paragraph({
            border: {
              top: { style: BorderStyle.SINGLE, size: 1, color: "CCCCCC" },
            },
            spacing: { before: 200, after: 100 },
          }),
          new Paragraph({
            children: [
              new TextRun({
                text: "This document was generated by Lawbite AI. This is not a substitute for professional legal advice. Please consult a qualified lawyer before relying on this document.",
                size: 18,
                italics: true,
                color: "888888",
              }),
            ],
          }),
        ],
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  saveAs(blob, `${title.replace(/[^a-zA-Z0-9]/g, "_")}.docx`);
}

export function exportAsPdf(content: string, title: string): void {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return;

  const formattedContent = content
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(/^## (.+)$/gm, "<h2>$1</h2>")
    .replace(/^# (.+)$/gm, "<h1>$1</h1>")
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/\n/g, "<br>");

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
    <head>
      <title>${title}</title>
      <style>
        body { font-family: Georgia, serif; max-width: 800px; margin: 0 auto; padding: 40px; line-height: 1.8; color: #333; }
        .header { text-align: right; color: #888; font-size: 12px; margin-bottom: 20px; }
        .title { font-size: 24px; font-weight: bold; margin-bottom: 20px; }
        .divider { border-top: 1px solid #ddd; margin: 20px 0; }
        .content { font-size: 14px; }
        .footer { border-top: 1px solid #ddd; margin-top: 40px; padding-top: 20px; font-size: 11px; color: #888; font-style: italic; }
        @media print { body { padding: 20px; } }
      </style>
    </head>
    <body>
      <div class="header">LAWBITE<br>${formatDate()}</div>
      <div class="title">${title}</div>
      <div class="divider"></div>
      <div class="content">${formattedContent}</div>
      <div class="footer">This document was generated by Lawbite AI. This is not a substitute for professional legal advice. Please consult a qualified lawyer before relying on this document.</div>
    </body>
    </html>
  `);
  printWindow.document.close();
  printWindow.print();
}
