import { jsPDF } from "jspdf";

export function generatePdfBlob(content: string, title: string): Blob {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPos = margin;

  // Header
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(136, 136, 136);
  doc.text("LAWBITE", pageWidth - margin, yPos, { align: "right" });
  yPos += 5;
  doc.text(
    new Date().toLocaleDateString("en-IN", {
      day: "numeric",
      month: "long",
      year: "numeric",
    }),
    pageWidth - margin,
    yPos,
    { align: "right" },
  );
  yPos += 12;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(0, 0, 0);
  const titleLines = doc.splitTextToSize(title, maxWidth);
  doc.text(titleLines, margin, yPos);
  yPos += titleLines.length * 8 + 4;

  // Divider
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 8;

  // Content
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(51, 51, 51);

  const lines = content.split("\n");

  for (const line of lines) {
    const trimmed = line.trim();

    if (!trimmed) {
      yPos += 4;
      continue;
    }

    // Detect headings (ALL CAPS or starts with #)
    const isHeading =
      (/^[A-Z][A-Z\s,()]+$/.test(trimmed) && trimmed.length > 5) ||
      trimmed.startsWith("# ");

    if (isHeading) {
      yPos += 4;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(0, 0, 0);
      const headingText = trimmed.replace(/^#\s*/, "");
      const headingLines = doc.splitTextToSize(headingText, maxWidth);
      doc.text(headingLines, margin, yPos);
      yPos += headingLines.length * 6 + 4;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(51, 51, 51);
      continue;
    }

    // Regular text
    const wrappedLines = doc.splitTextToSize(trimmed, maxWidth);

    for (const wLine of wrappedLines) {
      if (yPos > 270) {
        doc.addPage();
        yPos = margin;
      }
      doc.text(wLine, margin, yPos);
      yPos += 5.5;
    }

    yPos += 1;
  }

  // Footer
  if (yPos > 260) {
    doc.addPage();
    yPos = margin;
  }
  yPos += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(margin, yPos, pageWidth - margin, yPos);
  yPos += 6;
  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(136, 136, 136);
  const disclaimer =
    "This document was generated by LawBite AI. This is not a substitute for professional legal advice. Please consult a qualified lawyer before relying on this document.";
  const disclaimerLines = doc.splitTextToSize(disclaimer, maxWidth);
  doc.text(disclaimerLines, margin, yPos);

  return doc.output("blob");
}
