import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { headers } from "next/headers";
import { sendEmail } from "@/lib/email";
import { AUTHORITIES } from "@/lib/authorities";

export async function POST(request: NextRequest) {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const body = await request.json();
    const { to, subject, documentContent, complaintType, userEmail } = body;

    if (!to || !subject || !documentContent || !complaintType) {
      return NextResponse.json(
        {
          error:
            "Missing required fields: to, subject, documentContent, complaintType",
        },
        { status: 400 },
      );
    }

    const authority = AUTHORITIES[complaintType];
    if (!authority) {
      return NextResponse.json(
        { error: "Invalid complaint type" },
        { status: 400 },
      );
    }

    if (!authority.email) {
      return NextResponse.json(
        {
          error:
            "This complaint type does not support email filing. Please use the portal.",
          portalUrl: authority.portalUrl,
          portalName: authority.portalName,
        },
        { status: 400 },
      );
    }

    const htmlBody = `
      <div style="font-family: Georgia, serif; max-width: 700px; margin: 0 auto; padding: 20px; color: #333;">
        <div style="text-align: right; color: #888; font-size: 12px; margin-bottom: 20px;">
          Sent via LawBite AI<br>
          ${new Date().toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" })}
        </div>
        <div style="border-bottom: 1px solid #ddd; padding-bottom: 10px; margin-bottom: 20px;">
          <h2 style="margin: 0; font-size: 18px;">${subject}</h2>
          <p style="margin: 5px 0 0; font-size: 12px; color: #666;">
            From: ${session.user?.name || "LawBite User"} (${userEmail || session.user?.email || "N/A"})
          </p>
        </div>
        <div style="font-size: 14px; line-height: 1.8; white-space: pre-wrap;">${documentContent}</div>
        <div style="border-top: 1px solid #ddd; margin-top: 30px; padding-top: 15px; font-size: 11px; color: #888; font-style: italic;">
          This document was generated by LawBite AI. This is not a substitute for professional legal advice. Please consult a qualified lawyer before relying on this document.
        </div>
      </div>
    `;

    const emailResult = await sendEmail({
      to: authority.email,
      subject,
      html: htmlBody,
    });

    if (!emailResult.success) {
      return NextResponse.json({ error: emailResult.error }, { status: 500 });
    }

    return NextResponse.json({
      success: true,
      messageId: emailResult.messageId,
      sentTo: authority.email,
      authorityName: authority.name,
    });
  } catch {
    return NextResponse.json(
      { error: "Internal server error" },
      { status: 500 },
    );
  }
}
