#!/usr/bin/env python3
"""Create missing consumer & IT acts for S3 KB."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from s3_upload import create_act

ACTS = [
    {
        "id": "food-safety-standards-act",
        "title": "Food Safety and Standards Act, 2006",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Food Safety and Standards Act, 2006. Extends to whole of India. Came into force on 1st September 2006."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) food means any article of food, drink or substance intended for human consumption; (b) food business means any undertaking relating to food; (c) food safety officer means an officer appointed under section 30; (d) FSSAI means the Food Safety and Standards Authority of India established under section 4."},
            {"section": "4", "title": "Establishment of FSSAI",
             "text": "The Central Government shall establish the Food Safety and Standards Authority of India to lay down science-based standards for food, regulate food safety, and promote public health. FSSAI shall be a body corporate with perpetual succession."},
            {"section": "10", "title": "Functions of FSSAI",
             "text": "FSSAI shall: (a) lay down standards for food; (b) regulate manufacture, storage, distribution, sale and import of food; (c) provide scientific advice to Government; (d) promote awareness on food safety; (e) coordinate enforcement activities."},
            {"section": "16", "title": "Functions of Food Authority",
             "text": "The Food Authority shall: (a) frame regulations and standards for food; (b) conduct surveys and assessments; (c) license food businesses; (d) conduct inspections and audits; (e) take enforcement action for violations."},
            {"section": "23", "title": "Standards for food",
             "text": "The Food Authority shall, from time to time, specify by regulations the standards and guidelines for food, including contaminants, additives, labeling, and packaging requirements."},
            {"section": "26", "title": "General principles of food safety",
             "text": "The general principles of food safety include: (a) food safety is a matter of public health; (b) the primary responsibility for food safety rests with food business operators; (c) food standards shall be based on scientific evidence; (d) risk analysis shall be the basis for food safety decisions."},
            {"section": "30", "title": "Food Safety Officers",
             "text": "The State Government shall appoint Food Safety Officers for each district. The officers shall have the power to inspect food premises, take samples, and prosecute offences under this Act."},
            {"section": "31", "title": "Licensing of food businesses",
             "text": "No person shall carry on any food business except under a license granted under this Act. The license shall be granted by the Designated Officer on application and after inspection of premises."},
            {"section": "36", "title": "Registration of food businesses",
             "text": "Every food business operator shall register with the Designated Officer. The registration shall be in the prescribed form and shall be renewed annually."},
            {"section": "43", "title": "Food safety officer may take samples",
             "text": "A Food Safety Officer may take samples of food for analysis from any food business premises. The sample shall be sent to the accredited laboratory for analysis. The analysis report shall be admissible as evidence."},
            {"section": "50", "title": "Adulterated food",
             "text": "No person shall manufacture, sell or distribute any adulterated food. Adulterated food includes food which contains any substance which reduces its quality, or which contains any substance not prescribed, or which is not of the nature, substance or quality demanded."},
            {"section": "51", "title": "Misbranded food",
             "text": "No person shall manufacture, sell or distribute any misbranded food. Food is misbranded if its labeling is false or misleading, or it does not conform to prescribed standards, or it does not contain the required information."},
            {"section": "58", "title": "Penalties",
             "text": "Penalties for food safety violations: (a) minor contravention: fine up to Rs 25,000; (b) major contravention: fine up to Rs 5 lakh; (c) resulting in death: imprisonment up to life and fine up to Rs 10 lakh; (d) repeat offence: fine up to Rs 5 lakh and imprisonment up to 6 months."},
            {"section": "63", "title": "Offences by companies",
             "text": "Where an offence has been committed by a company, every person who was in charge of and responsible for the company's conduct shall be deemed guilty. The company shall also be punished with fine."},
            {"section": "69", "title": "Compounding of offences",
             "text": "Any offence under this Act which is not punishable with imprisonment may be compounded by the Food Safety Officer or the Designated Officer. The compounding fee shall be as prescribed."},
        ]
    },
    {
        "id": "drugs-cosmetics-act",
        "title": "Drugs and Cosmetics Act, 1940",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Drugs and Cosmetics Act, 1940. Extends to whole of India. Came into force on 1st April 1940."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) drug includes medicines for internal or external use of human beings or animals; (b) cosmetics means articles intended to be rubbed, poured or sprinkled on the human body for cleansing, beautifying, promoting attractiveness; (c) manufacturer means a person engaged in manufacturing of drugs or cosmetics; (d) pharmacy means a shop or premises where drugs are dispensed."},
            {"section": "3", "title": "Regulation of import of drugs",
             "text": "No person shall import any drug or cosmetic except with the permission of the Central Government. The import shall comply with prescribed standards and requirements."},
            {"section": "5", "title": "Standards of drugs and cosmetics",
             "text": "The Central Government shall prescribe standards for drugs and cosmetics, including standards of purity, quality, strength, and packaging. The standards shall be consistent with international standards."},
            {"section": "10", "title": "Licensing of manufacture",
             "text": "No person shall manufacture for sale, distribute or exhibit for sale any drug or cosmetic except under a license granted under this Act. The license shall be granted by the State Licensing Authority."},
            {"section": "14", "title": "License for sale of drugs",
             "text": "No person shall sell, offer for sale, or distribute any drug except under a license granted under this Act. The license shall be granted by the Drug Inspector."},
            {"section": "17", "title": "Prohibition of manufacture and sale of certain drugs",
             "text": "The Central Government may prohibit the manufacture, sale or distribution of any drug which is considered to be injurious to health, or which does not meet prescribed standards."},
            {"section": "18", "title": "Misbranded drugs",
             "text": "A drug shall be deemed to be misbranded if: (a) it is not of the nature, substance or quality demanded; (b) its label is false or misleading; (c) it does not contain the required ingredients; (d) it is not in the prescribed packaging."},
            {"section": "20", "title": "Adulterated drugs",
             "text": "A drug shall be deemed to be adulterated if: (a) it contains any substance which makes it injurious to health; (b) it contains any substance not prescribed; (c) it has deteriorated or has been contaminated; (d) it does not meet prescribed standards."},
            {"section": "26A", "title": "Ban on certain drugs",
             "text": "The Central Government may, by notification, ban the manufacture, sale or distribution of any drug which is considered to be dangerous or which has no therapeutic value."},
            {"section": "27", "title": "Penalties",
             "text": "Penalties for contravention: (a) sale of adulterated or misbranded drug: imprisonment up to 1 year, or fine up to Rs 5,000, or both; (b) manufacture of adulterated or misbranded drug: imprisonment up to 3 years, or fine up to Rs 5,000, or both; (c) repeat offence: imprisonment up to 5 years and fine up to Rs 10,000."},
            {"section": "32", "title": "Powers of Drug Inspector",
             "text": "A Drug Inspector may: (a) inspect any premises where drugs are manufactured, stored or sold; (b) take samples for analysis; (c) seize records and documents; (d) arrest persons committing offences."},
            {"section": "33", "title": "Government Analyst",
             "text": "The State Government may appoint Government Analysts to analyse drug samples. The analysis report of a Government Analyst shall be admissible as evidence in court."},
            {"section": "34", "title": "Cognizance of offences",
             "text": "No court shall take cognizance of an offence under this Act except upon complaint made by a Drug Inspector or an officer authorised by the Government."},
        ]
    },
    {
        "id": "dpdp-act",
        "title": "Digital Personal Data Protection Act, 2023",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Digital Personal Data Protection Act, 2023. Extends to whole of India, including processing of digital personal data outside India if related to offering goods or services in India. Came into force on different dates by notification."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) data fiduciary means any person who alone or in conjunction with others determines the purpose and means of processing personal data; (b) data principal means the individual to whom personal data relates; (c) data processor means any person who processes personal data on behalf of a data fiduciary; (d) personal data means any data about an individual who is identifiable by or in relation to such data; (e) consent means any freely given, specific, informed, unconditional indication of the data principal's wishes."},
            {"section": "3", "title": "Applicability",
             "text": "This Act applies to: (a) processing of digital personal data within India; (b) processing of digital personal data outside India if related to offering goods or services to data principals in India, or profiling of data principals in India. It does not apply to data processed by an individual for personal or domestic purposes, or data made publicly available."},
            {"section": "4", "title": "Processing of digital personal data",
             "text": "Processing of personal data shall be lawful only if: (a) the data principal has given consent; or (b) the processing is for compliance with a law or contract; or (c) the processing is necessary for employment purposes; or (d) the processing is necessary for the exercise of functions of the State; or (e) the processing is necessary for medical emergency; or (f) the processing is necessary for public interest."},
            {"section": "5", "title": "Notice to data principal",
             "text": "Before processing personal data, the data fiduciary shall provide a notice to the data principal in clear and plain language, containing: (a) a description of the personal data collected; (b) the purpose of processing; (c) the manner of processing; (d) the rights of the data principal; (e) the grievance redressal mechanism."},
            {"section": "6", "title": "Consent",
             "text": "Before processing personal data, the data fiduciary shall obtain consent from the data principal. The consent shall be: (a) freely given; (b) specific; (c) informed; (d) unconditional; (e) unambiguous; (f) affirmative action by the data principal. The data fiduciary shall provide an easy mechanism for withdrawal of consent."},
            {"section": "7", "title": "Rights of data principal",
             "text": "The data principal shall have the right to: (a) be informed about the processing of personal data; (b) have access to personal data; (c) correct and erase personal data; (d) grievance redressal; (e) nominate another individual to exercise rights in case of death or incapacity."},
            {"section": "8", "title": "Obligations of data fiduciary",
             "text": "The data fiduciary shall: (a) process personal data for lawful purposes only; (b) take reasonable security safeguards; (c) notify the Board and data principals of any data breach; (d) delete personal data after the purpose is fulfilled; (e) not retain personal data beyond necessary period; (f) ensure compliance with the Act."},
            {"section": "9", "title": "Obligations of data principal",
             "text": "The data principal shall: (a) comply with applicable laws; (b) provide only necessary personal data; (c) not impersonate another person; (d) not file false complaints."},
            {"section": "10", "title": "Processing of personal data of children",
             "text": "A data fiduciary shall not process personal data of a child (below 18 years) unless: (a) verifiable consent of the parent is obtained; or (b) processing is necessary for employment; or (c) processing is necessary for compliance with law. A data fiduciary shall not undertake tracking or behavioral monitoring of children, or target advertising to children."},
            {"section": "11", "title": "Data Protection Board of India",
             "text": "The Central Government shall establish the Data Protection Board of India to hear complaints and adjudicate disputes under this Act. The Board shall consist of a Chairperson and members appointed by the Central Government."},
            {"section": "16", "title": "Powers of Board",
             "text": "The Board may: (a) inquire into complaints of data breach; (b) direct data fiduciaries to take corrective action; (c) impose penalties as prescribed; (d) issue directions for data protection; (e) hear appeals against its own orders."},
            {"section": "25", "title": "Penalties",
             "text": "Penalties for contravention: (a) failure to take reasonable security safeguards: up to Rs 250 crore; (b) failure to notify data breach: up to Rs 200 crore; (c) non-compliance with obligations regarding children: up to Rs 200 crore; (d) failure to comply with Board directions: up to Rs 50 crore; (e) breach of any other provision: up to Rs 50 crore."},
            {"section": "26", "title": "Compounding of offences",
             "text": "The Board may compound offences under this Act with the prior approval of the Central Government. The compounding fee shall not be less than 5% of the prescribed penalty."},
            {"section": "28", "title": "Extraterritorial jurisdiction",
             "text": "This Act shall apply to processing of digital personal data outside India if: (a) the processing relates to offering goods or services to data principals in India; or (b) the processing involves profiling of data principals in India. Any data fiduciary outside India shall appoint a representative in India."},
        ]
    },
    {
        "id": "aadhaar-act",
        "title": "Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Aadhaar (Targeted Delivery of Financial and Other Subsidies, Benefits and Services) Act, 2016. Extends to whole of India. Came into force on 12th September 2016."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) Aadhaar number means a 12-digit unique identification number issued to residents of India; (b) biometric information means photograph, finger prints, iris scan or other biological attributes; (c) UIDAI means the Unique Identification Authority of India established under section 11; (d) resident means an individual who has resided in India for a period of 182 days in the preceding 12 months."},
            {"section": "3", "title": "Aadhaar number",
             "text": "Every resident shall be entitled to obtain an Aadhaar number by submitting demographic and biometric information. The Aadhaar number shall be a unique 12-digit number issued by UIDAI. No person shall have more than one Aadhaar number."},
            {"section": "4", "title": "Proof of Aadhaar number",
             "text": "An Aadhaar number, upon due verification, shall be accepted as proof of identity. No person shall be denied any service or benefit for lack of Aadhaar number, subject to exceptions prescribed by the Central Government."},
            {"section": "8", "title": "Authentication of Aadhaar number",
             "text": "The Aadhaar number may be authenticated by providing biometric or demographic information. The authentication may be done online or offline. The requesting entity shall ensure the security of authentication data."},
            {"section": "11", "title": "Establishment of UIDAI",
             "text": "The Central Government shall establish the Unique Identification Authority of India for the purpose of issuing Aadhaar numbers. UIDAI shall be headed by the Chairperson and consist of members appointed by the Central Government."},
            {"section": "12", "title": "Functions of UIDAI",
             "text": "UIDAI shall: (a) assign Aadhaar numbers to residents; (b) maintain the Aadhaar database; (c) authenticate Aadhaar numbers; (d) ensure security and confidentiality of identity information; (e) promote the use of Aadhaar for targeted delivery of subsidies."},
            {"section": "23", "title": "Security and confidentiality of information",
             "text": "UIDAI shall ensure the security and confidentiality of identity information and authentication records. No core biometric information shall be used for any purpose other than Aadhaar issuance and authentication."},
            {"section": "27", "title": "Restriction on sharing information",
             "text": "No person shall have access to the core biometric information of any individual. The identity information may be shared only for the purposes of authentication, or as directed by the Central Government in the interest of national security."},
            {"section": "28", "title": "Security safeguards",
             "text": "UIDAI shall implement appropriate technical and organizational security safeguards to protect the identity information. The safeguards shall include encryption, access controls, audit trails, and regular security assessments."},
            {"section": "29", "title": "Prohibition on sharing of core biometric information",
             "text": "No entity shall share, display or publish any core biometric information. Core biometric information includes fingerprints, iris scans and other biological attributes used for authentication."},
            {"section": "30", "title": "Access to own information",
             "text": "Every resident shall have the right to access their own identity information. The information may be obtained from UIDAI on application and payment of prescribed fee."},
            {"section": "33", "title": "Disclosure of identity information",
             "text": "The identity information may be disclosed: (a) on the direction of a competent court; (b) on the order of the Central Government in the interest of national security; (c) to the extent necessary for authentication. The disclosure shall be recorded and reported to UIDAI."},
            {"section": "35", "title": "Use of Aadhaar for subsidies",
             "text": "The Central Government may require Aadhaar number for the purpose of establishing identity for targeted delivery of subsidies, benefits and services funded from the Consolidated Fund of India. The requirement shall be subject to exceptions for persons who cannot obtain Aadhaar."},
            {"section": "40", "title": "Penalty for unauthorized access",
             "text": "Whoever, without authorization, accesses the Aadhaar database or authentication records shall be punished with imprisonment up to 3 years, or fine up to Rs 10 lakh, or both."},
            {"section": "41", "title": "Penalty for tampering with database",
             "text": "Whoever, with intent to cause damage, tampers with or accesses the Aadhaar database shall be punished with imprisonment up to 3 years, or fine up to Rs 10 lakh, or both."},
            {"section": "42", "title": "Penalty for unauthorized use of identity information",
             "text": "Whoever, without authorization, uses or discloses identity information shall be punished with imprisonment up to 3 years, or fine up to Rs 10 lakh, or both."},
            {"section": "43", "title": "Penalty for unauthorized disclosure",
             "text": "Whoever discloses core biometric information or identity information without authorization shall be punished with imprisonment up to 3 years, or fine up to Rs 10 lakh, or both."},
        ]
    },
    {
        "id": "right-to-information-act",
        "title": "Right to Information Act, 2005",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Right to Information Act, 2005. Extends to whole of India. Came into force on 12th October 2005."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) information means any material in any form including records, documents, memos, e-mails, opinions, press releases, orders, logbooks, contracts, reports, samples; (b) public authority means any authority or body or institution of self-government established by the Constitution, laws, or notifications; (c) right to information means the right to obtain information from a public authority under this Act; (d) information officer means the officer designated under section 5."},
            {"section": "3", "title": "Rights of citizens",
             "text": "Subject to provisions of this Act, all citizens shall have the right to information. The right extends to access information held by or under the control of public authorities."},
            {"section": "4", "title": "Proactive disclosure",
             "text": "Every public authority shall, on its own motion, publish information as prescribed including: (a) the particulars of its organization; (b) the powers and duties of its officers; (c) the procedure followed in decision making; (d) the norms set for discharge of functions; (e) the rules, regulations, instructions and manuals; (f) the categories of documents held; (g) the particulars of any arrangement for consultation with public; (h) a statement of the boards, councils, committees; (i) a directory of officers and employees; (j) the monthly remuneration; (k) the budget allocated; (l) the manner of execution of subsidy programmes; (m) the particulars of recipients of concessions, permits; (n) the information available in electronic form; (o) the facilities available for obtaining information."},
            {"section": "5", "title": "Designation of Public Information Officers",
             "text": "Every public authority shall designate: (a) a Central Public Information Officer at each office; (b) a State Public Information Officer at each office; (c) a Central Assistant Public Information Officer; (d) a State Assistant Public Information Officer. The designated officers shall receive and process requests for information."},
            {"section": "6", "title": "Request for obtaining information",
             "text": "A person desiring to obtain information shall submit a request to the Public Information Officer or Assistant Public Information Officer. The request shall be in writing, in English or Hindi or the official language of the area, and shall indicate the information sought."},
            {"section": "7", "title": "Disposal of request",
             "text": "The Public Information Officer shall: (a) provide the information within 30 days of receipt of the request; (b) inform the applicant of the cost of obtaining the information; (c) deny the request if the information is exempt under section 8."},
            {"section": "8", "title": "Exemptions from disclosure",
             "text": "Information shall be exempt from disclosure if: (a) it is related to sovereignty and integrity of India, security of the State; (b) it is forbidden by a court of law; (c) it would cause breach of privilege of Parliament or State Legislature; (d) it includes commercial confidence; (e) it is received in fiduciary relationship; (f) it would endanger life or physical safety; (g) it relates to law enforcement; (h) it is cabinet papers; (i) it includes personal information with no public interest."},
            {"section": "9", "title": "Grounds for rejection",
             "text": "A request may be rejected if: (a) the information is exempt under section 8; (b) the disclosure would cause damage to the sovereignty, integrity or security of India; (c) the disclosure would cause breach of privilege; (d) the disclosure would endanger life or physical safety; (e) the disclosure would obstruct investigation or prosecution."},
            {"section": "11", "title": "Third party information",
             "text": "Where a request relates to third party information, the Public Information Officer shall give a written notice to the third party within 5 days. The third party may make a representation against disclosure within 10 days. The Public Information Officer shall consider the representation and decide whether to disclose the information."},
            {"section": "12", "title": "Fee",
             "text": "No fee shall be charged for: (a) obtaining information under section 4; (b) obtaining information by persons belonging to Below Poverty Line. For other persons, the fee shall be as prescribed by the Central Government or State Government."},
            {"section": "13", "title": "Mode of payment of fee",
             "text": "The fee may be paid: (a) in cash; (b) by demand draft or banker's cheque; (c) by electronic means. The fee shall be payable at the time of submitting the request."},
            {"section": "18", "title": "Powers and functions of Information Commissions",
             "text": "The Central Information Commission and State Information Commissions shall: (a) receive complaints regarding denial of information; (b) inquire into complaints; (c) order disclosure of information; (d) impose penalties for non-compliance; (e) promote awareness of the Act."},
            {"section": "19", "title": "Appeal",
             "text": "Any person aggrieved by a decision of the Public Information Officer may file: (a) first appeal before the Appellate Authority within 30 days; (b) second appeal before the Information Commission within 90 days. The Information Commission may order disclosure of information and impose penalty."},
            {"section": "20", "title": "Penalty",
             "text": "The Information Commission may impose a penalty of Rs 250 per day on the Public Information Officer for: (a) failure to furnish information within 30 days; (b) failure to give a notice of denial; (c) failure to provide information as required; (d) giving deliberately incorrect or incomplete information. The total penalty shall not exceed Rs 25,000."},
            {"section": "26", "title": "Protection of action taken in good faith",
             "text": "No suit, prosecution or legal proceeding shall lie against the Public Information Officer or the Information Commission for anything done in good faith under this Act."},
        ]
    },
    {
        "id": "consumer-protection-act-amended",
        "title": "Consumer Protection Act, 2019 (Key Provisions)",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Consumer Protection Act, 2019. Extends to whole of India. Came into force on 20th July 2020, replacing the Consumer Protection Act, 1986."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) consumer means any person who buys goods or hires services for consideration; (b) consumer dispute means a dispute where the complainant alleges unfair trade practice, defective goods, deficiency in services; (c) product liability means the responsibility of a product manufacturer or seller for damages caused by defective products; (d) e-commerce means buying or selling of goods or services over digital or electronic network."},
            {"section": "3", "title": "Consumer Protection Councils",
             "text": "The Central Government shall establish the Central Consumer Protection Council, and the State Governments shall establish State Consumer Protection Councils. The Councils shall promote and protect the rights of consumers."},
            {"section": "10", "title": "Central Consumer Protection Authority",
             "text": "The Central Government shall establish the Central Consumer Protection Authority (CCPA) to regulate matters relating to violation of consumer rights, unfair trade practices, and false or misleading advertisements. The CCPA may: (a) inquire into violations; (b) order recall of unsafe goods; (c) order refund of prices; (d) impose penalties."},
            {"section": "17", "title": "District Commission",
             "text": "The State Government shall establish a District Consumer Disputes Redressal Commission in each district. The District Commission shall have jurisdiction to entertain complaints where the value of goods or services does not exceed Rs 50 lakh."},
            {"section": "20", "title": "State Commission",
             "text": "The State Government shall establish a State Consumer Disputes Redressal Commission. The State Commission shall have jurisdiction to entertain complaints where the value exceeds Rs 50 lakh but does not exceed Rs 2 crore, and appeals against District Commission orders."},
            {"section": "21", "title": "National Commission",
             "text": "The Central Government shall establish the National Consumer Disputes Redressal Commission. The National Commission shall have jurisdiction to entertain complaints where the value exceeds Rs 2 crore, and appeals against State Commission orders."},
            {"section": "34", "title": "Who may file a complaint",
             "text": "A complaint may be filed by: (a) a consumer; (b) any recognized consumer association; (c) one or more consumers on behalf of numerous consumers; (d) the Central Government or State Government; (e) a legal heir or representative in case of consumer's death."},
            {"section": "35", "title": "Complaint to District Commission",
             "text": "A complaint may be filed before the District Commission where: (a) the value of goods or services does not exceed Rs 50 lakh; (b) the complainant resides or works within the jurisdiction; (c) the cause of action arose within the jurisdiction. The complaint shall be filed within 2 years from the date of cause of action."},
            {"section": "38", "title": "Relief available",
             "text": "The District Commission may order: (a) removal of defects from goods; (b) replacement of goods; (c) refund of price; (d) compensation for loss or injury; (e) costs of the proceedings; (f) discontinuation of unfair trade practice; (g) not to offer hazardous goods for sale; (h) to provide adequate safety measures."},
            {"section": "42", "title": "Appeal to State Commission",
             "text": "Any person aggrieved by an order of the District Commission may file an appeal before the State Commission within 45 days of the order. The State Commission may confirm, modify or set aside the order."},
            {"section": "47", "title": "Appeal to National Commission",
             "text": "Any person aggrieved by an order of the State Commission may file an appeal before the National Commission within 30 days of the order. The National Commission may confirm, modify or set aside the order."},
            {"section": "49", "title": "Product liability",
             "text": "A product liability action may be brought against a product manufacturer or seller for damages caused by a defective product. The manufacturer shall be liable if: (a) the product had a defect; (b) the defect caused injury or damage; (c) the product was not safe for its intended use."},
            {"section": "69", "title": "Penalties for false or misleading advertisements",
             "text": "The CCPA may impose penalties for false or misleading advertisements: (a) first offence: fine up to Rs 10 lakh; (b) subsequent offence: fine up to Rs 50 lakh. The CCPA may also order discontinuation of the advertisement and costs of proceedings."},
            {"section": "72", "title": "E-commerce consumer protection",
             "text": "No e-commerce entity shall: (a) impose cancellation charges on consumers after confirmation of orders; (b) refuse to accept return of goods without valid reason; (c) misrepresent products or services; (d) engage in unfair trade practices. The CCPA may take action against e-commerce violations."},
            {"section": "87", "title": "Offences by companies",
             "text": "Where an offence under this Act has been committed by a company, every person who was in charge of and responsible for the company's conduct shall be deemed guilty. The company shall also be punished with fine."},
            {"section": "89", "title": "Compounding of offences",
             "text": "Any offence under this Act which is not punishable with imprisonment may be compounded by the District Commission or the State Commission. The compounding fee shall be as prescribed."},
        ]
    },
]

if __name__ == "__main__":
    print("Creating consumer & IT acts...")
    for act in ACTS:
        create_act(act["id"], act["title"], act["sections"])
    print(f"Done: {len(ACTS)} acts created.")
