#!/usr/bin/env python3
"""Create missing family & personal law acts for S3 KB."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from s3_upload import create_act

ACTS = [
    {
        "id": "muslim-personal-law-act",
        "title": "Muslim Personal Law (Shariat) Application Act, 1937",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Muslim Personal Law (Shariat) Application Act, 1937. Extends to whole of India. Came into force on 7th October 1937."},
            {"section": "2", "title": "Application of Muslim Personal Law",
             "text": "Notwithstanding any custom or usage to the contrary, in all questions regarding succession, contracts, marriage, dissolution of marriage including talaq, muta, dower, guardianship, gifts, trusts and trust properties, and wakfs (other than wakfs of properties governed by the Indian Trusts Act, 1882, or the Transfer of Property Act, 1882), the rule of decision in cases where the parties are Muslims shall be the Muslim Personal Law (Shariat)."},
            {"section": "3", "title": "Power to make rules",
             "text": "The State Government may make rules to carry out the purposes of this Act. Such rules shall be published in the Official Gazette and shall come into force on the date of publication."},
            {"section": "4", "title": "Non-applicability of certain laws",
             "text": "Nothing in this Act shall be deemed to affect the jurisdiction of a court to grant a decree for divorce under any law for the time being in force. The Act applies to Muslims who have not expressly or by implication opted out of Shariat."},
            {"section": "5", "title": "Triple Talaq — prohibition under Muslim Women Act 2019",
             "text": "The Muslim Women (Protection of Rights on Marriage) Act, 2019 declares triple talaq (talaq-e-biddat) void and illegal. However, this Act does not repeal the Shariat Application Act. Muslim personal law continues to govern succession, marriage, dower, gifts, trusts, and wakfs. Triple talaq pronounced in any form (spoken, written, or electronic) is void and punishable with up to 3 years imprisonment."},
        ]
    },
    {
        "id": "dissolution-of-muslim-marriages-act",
        "title": "Dissolution of Muslim Marriages Act, 1939",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Dissolution of Muslim Marriages Act, 1939. Extends to whole of India. Came into force on 17th March 1939."},
            {"section": "2", "title": "Grounds for decree for dissolution of marriage",
             "text": "A woman married under Muslim law shall be entitled to obtain a decree for the dissolution of her marriage on any one or more of the following grounds: (a) where the husband's whereabouts are unknown for a period of 4 years; (b) where the husband has failed to provide maintenance for 2 years; (c) where the husband has been sentenced to imprisonment for 7 or more years; (d) where the husband has failed to perform marital obligations for 3 years; (e) where the husband was impotent at the time of marriage and continues to be so; (f) where the husband has become insane for 2 years or is afflicted with a virulent venereal disease; (g) where the husband has more than one wife and does not treat her equitably; (h) where the husband has been cruel to her; (i) where the husband denies her the right of mahr agreed upon or the dower. Note: The Personal Laws (Amendment) Act, 2019 removed 'leprosy' as a ground from this section."},
            {"section": "3", "title": "Non-residence",
             "text": "A husband's failure to provide maintenance for 2 years shall be a ground for dissolution even if he is residing in the same town or area as his wife, provided he has failed to maintain her during that period."},
            {"section": "4", "title": "Dower",
             "text": "Where the husband has denied the wife the right of mahr agreed upon or the dower, it shall be a ground for dissolution of marriage. The wife may also claim her dower in the dissolution proceedings."},
            {"section": "5", "title": "Effect of decree",
             "text": "A decree for dissolution of marriage shall have the effect of dissolving the marriage from the date on which it becomes final. The wife shall be entitled to claim maintenance during the iddat period after the dissolution."},
            {"section": "6", "title": "Iddat period",
             "text": "After a decree for dissolution of marriage, the woman shall observe the iddat period as prescribed by Muslim law. During the iddat period, the husband shall be liable to maintain the wife."},
            {"section": "7", "title": "Triple Talaq — Muslim Women (Protection of Rights on Marriage) Act, 2019",
             "text": "The Muslim Women (Protection of Rights on Marriage) Act, 2019 (Act No. 20 of 2019) made triple talaq (talaq-e-biddat) void and illegal. Any pronouncement of talaq by a Muslim husband upon his wife by words, spoken or written or in electronic form, shall be void and illegal. The husband is punishable with imprisonment up to 3 years and fine. The wife is entitled to subsistence allowance for herself and dependent children, and custody of minor children. The Act applies retrospectively from 19 September 2018. Note: This is a separate Act and does not repeal the DMDA 1939, which continues to apply for judicial divorce on other grounds."},
            {"section": "8", "title": "Maintenance under Section 125 CrPC — Supreme Court 2024 ruling",
             "text": "In July 2024, the Supreme Court (Mohd. Abdul Samad v. State of Telangana) ruled that Muslim women, including those divorced by triple talaq, are entitled to claim maintenance under Section 125 of the CrPC irrespective of their personal law. The 1986 Muslim Women Act does not take away this right. The option lies with the woman to seek remedy under either Section 125 CrPC or the 1986 Act, or both. This applies to ALL married women including Muslim women."},
            {"section": "9", "title": "Recovery of wedding gifts — Supreme Court 2025 ruling",
             "text": "In December 2025, the Supreme Court held that a divorced Muslim woman is entitled to recover money, gold, and other articles gifted at the wedding from her husband. Section 3 of the Muslim Women (Protection of Rights on Divorce) Act, 1986 entitles the woman to receive mahr (dower) and all properties given to her before, at the time of, or after the wedding."},
            {"section": "10", "title": "Talaq-e-Hasan — pending Supreme Court proceedings 2026",
             "text": "Talaq-e-Hasan is a form of Muslim divorce where the husband pronounces 'talaq' once per month for three consecutive months, with a waiting period between each pronouncement. This is distinct from triple talaq (talaq-e-biddat) which is criminalized under the 2019 Act. The Supreme Court is currently (2026) hearing a challenge to the validity of Talaq-e-Hasan and may refer the matter to a larger Constitution Bench."},
        ]
    },
    {
        "id": "indian-divorce-act",
        "title": "Indian Divorce Act, 1869",
        "sections": [
            {"section": "1", "title": "Short title and extent",
             "text": "This Act may be called the Indian Divorce Act, 1869. It extends to the whole of India. It applies to Christians and persons whose marriages are registered under the Indian Christian Marriage Act, 1872."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) High Court means the High Court having jurisdiction; (b) marriage means a marriage solemnized under the Indian Christian Marriage Act, 1872; (c) prescribed means prescribed by rules made under this Act."},
            {"section": "3", "title": "Grounds for divorce",
             "text": "Any marriage solemnized under the Indian Christian Marriage Act, 1872, may be dissolved on the following grounds: (a) adultery; (b) cruelty; (c) desertion for 2 years; (d) conversion to another religion; (e) unsoundness of mind; (f) leprosy; (g) venereal disease; (h) presumption of death; (i) non-residence for 2 years."},
            {"section": "10", "title": "Preliminary proceedings",
             "text": "Before filing a petition for divorce, the petitioner must serve a notice on the other party and attempt reconciliation. The court may refer the parties to a counsellor or a priest for reconciliation."},
            {"section": "11", "title": "Petition for divorce",
             "text": "A petition for dissolution of marriage may be presented to the High Court by either party on any of the grounds specified in section 3. The petition shall state the facts of the case and the relief sought."},
            {"section": "12", "title": "Duty of court",
             "text": "The court shall, on presentation of the petition, inquire into the truth of the allegations and satisfy itself that the marriage was solemnized and that the petitioner is entitled to relief. The court may grant a decree for dissolution or for judicial separation."},
            {"section": "13", "title": "Judicial separation",
             "text": "The court may decree a judicial separation instead of dissolution of marriage. Judicial separation means that the parties are no longer bound to live together, but the marriage is not dissolved."},
            {"section": "14", "title": "Alimony and maintenance",
             "text": "The court may order the husband to pay alimony or maintenance to the wife during the proceedings and after the decree. The amount shall be determined based on the income and means of the parties."},
            {"section": "23", "title": "Custody of children",
             "text": "The court may make such orders as it thinks fit regarding the custody, maintenance and education of children of the marriage. The welfare of the child shall be the paramount consideration."},
            {"section": "34", "title": "Protection of parties",
             "text": "The court may make orders for the protection of the parties during the proceedings, including orders for residence, protection from violence, and interim maintenance."},
        ]
    },
    {
        "id": "parsi-marriage-divorce-act",
        "title": "Parsi Marriage and Divorce Act, 1936",
        "sections": [
            {"section": "1", "title": "Short title and extent",
             "text": "This Act may be called the Parsi Marriage and Divorce Act, 1936. It applies to Parsis in the whole of India."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) Parsi means a Parsi Zoroastrian; (b) matrimony means a Parsi marriage solemnized under this Act; (c) court means the court constituted under this Act; (d) children of the marriage means children born of the marriage or children legitimized under this Act."},
            {"section": "3", "title": "Solemnization of Parsi marriages",
             "text": "Every Parsi marriage shall be solemnized according to the Parsi仪式, in the presence of a Parsi priest and at least two witnesses. The marriage shall be registered in the Marriage Register maintained under this Act."},
            {"section": "4", "title": "Registration of marriages",
             "text": "Every Parsi marriage shall be registered within 7 days of solemnization. The priest who solemnizes the marriage shall enter the details in the Marriage Register and sign the entry. Failure to register does not invalidate the marriage."},
            {"section": "5", "title": "Grounds for divorce",
             "text": "A Parsi marriage may be dissolved on the following grounds: (a) adultery; (b) cruelty; (c) desertion for 2 years; (d) conversion to another religion; (e) unsoundness of mind; (f) leprosy; (g) venereal disease; (h) presumption of death; (i) non-residence for 2 years; (j) mutual consent."},
            {"section": "32", "title": "Petition for divorce",
             "text": "A petition for dissolution of marriage may be presented to the court by either party on any of the grounds specified in section 5. The petition shall be filed within 2 years of the ground arising."},
            {"section": "33", "title": "Duty of court",
             "text": "The court shall inquire into the truth of the allegations and may refer the parties to a priest or counsellor for reconciliation. If reconciliation fails, the court may grant a decree for dissolution."},
            {"section": "39", "title": "Alimony and maintenance",
             "text": "The court may order the husband to pay alimony or maintenance to the wife during the proceedings and after the decree. The amount shall not exceed Rs 500 per month unless the court directs otherwise."},
            {"section": "41", "title": "Custody of children",
             "text": "The court may make orders regarding the custody, maintenance and education of children of the marriage. The welfare of the child shall be the paramount consideration."},
            {"section": "42", "title": "Property rights",
             "text": "The court may make orders regarding the division of property between the parties. The court shall consider the contributions of each party to the marriage and the needs of the parties."},
        ]
    },
    {
        "id": "indian-christian-marriage-act",
        "title": "Indian Christian Marriage Act, 1872",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Indian Christian Marriage Act, 1872. It extends to the whole of India except the territories which, immediately before the 1st November 1956, were comprised in Part B States."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) Christian means a person who professes the Christian religion; (b) marriage means a Christian marriage; (c) minister means a clergyman of any church; (d) Marriage Registrar means a person appointed to register marriages under this Act."},
            {"section": "3", "title": "Marriages to be solemnized according to Act",
             "text": "Every Christian marriage in India shall be solemnized according to the provisions contained in this Act. No marriage shall be valid unless solemnized in accordance with this Act."},
            {"section": "4", "title": "Who may solemnize marriages",
             "text": "A Christian marriage may be solemnized by: (a) any minister of religion licensed to solemnize marriages; (b) any clergyman of any church; (c) any person licensed under section 5 to solemnize marriages."},
            {"section": "5", "title": "Licensing of persons to solemnize marriages",
             "text": "The State Government may license any person to solemnize marriages under this Act. The license may be revoked at any time by the State Government."},
            {"section": "6", "title": "Requirements for valid marriage",
             "text": "A Christian marriage is valid if: (a) neither party has a husband or wife living; (b) neither party is of unsound mind; (c) the parties are not within the degrees of prohibited relationship; (d) notice has been given to the Marriage Registrar; (e) the marriage has been solemnized in the presence of two witnesses."},
            {"section": "7", "title": "Notice of intended marriage",
             "text": "Before solemnizing a marriage, the parties shall give notice to the Marriage Registrar of the district where one of the parties resides. The notice shall be published for 14 days."},
            {"section": "10", "title": "Registration of marriages",
             "text": "Every marriage shall be registered with the Marriage Registrar of the district where the marriage is solemnized. The parties shall sign the Marriage Register in the presence of two witnesses."},
            {"section": "14", "title": "Offences",
             "text": "Any person who solemnizes a marriage in contravention of this Act, or makes a false entry in the Marriage Register, shall be punished with imprisonment up to 7 years, or fine, or both."},
            {"section": "18", "title": "Powers of Marriage Registrar",
             "text": "The Marriage Registrar may inquire into the validity of a proposed marriage and refuse to register it if not satisfied that the requirements of this Act have been complied with."},
        ]
    },
    {
        "id": "prohibition-child-marriage-act",
        "title": "Prohibition of Child Marriage Act, 2006",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Prohibition of Child Marriage Act, 2006. Extends to whole of India. Came into force on 1st January 2007, replacing the Child Marriage Restraint Act, 1929."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) child means a male below 21 years and a female below 18 years; (b) child marriage means a marriage where either party is a child; (c) minor means a person who is not an adult; (d) marriage means any marriage, whether or not solemnized."},
            {"section": "3", "title": "Child marriages void ab initio",
             "text": "Any child marriage solemnized after the commencement of this Act shall be void ab initio (void from the beginning). A child marriage shall have no legal effect."},
            {"section": "4", "title": "Punishment for solemnizing child marriage",
             "text": "Any person who performs, conducts, directs or facilitates any child marriage shall be punished with rigorous imprisonment which may extend to 2 years, or fine which may extend to Rs 1 lakh, or both."},
            {"section": "5", "title": "Punishment for child marriage between a child and an adult",
             "text": "Any adult male who contracts a child marriage shall be punished with rigorous imprisonment which may extend to 2 years, or fine which may extend to Rs 1 lakh, or both."},
            {"section": "6", "title": "Punishment for parent or guardian of child",
             "text": "Any parent or guardian of a child who promotes, permits or conducts a child marriage shall be punished with rigorous imprisonment which may extend to 2 years, or fine which may extend to Rs 1 lakh, or both."},
            {"section": "7", "title": "Punishment for promoting child marriage",
             "text": "Any person who promotes, permits or facilitates a child marriage shall be punished with rigorous imprisonment which may extend to 2 years, or fine which may extend to Rs 1 lakh, or both."},
            {"section": "9", "title": "Child marriage prohibition officer",
             "text": "The State Government shall appoint Child Marriage Prohibition Officers in every district. The Officer shall have the power to prevent child marriages, file complaints, and rescue children from child marriages."},
            {"section": "10", "title": "Power to issue injunction",
             "text": "Any court having jurisdiction may issue an injunction prohibiting any child marriage. Any person who disobeys the injunction shall be punished with imprisonment up to 2 years, or fine, or both."},
            {"section": "11", "title": "Marriage of a minor to be voidable",
             "text": "A child marriage may be annulled by a court on petition by: (a) the child; (b) the child's parent or guardian; (c) a Child Marriage Prohibition Officer. The court may declare the marriage void and make orders for custody, maintenance and return of the child."},
            {"section": "12", "title": "Maintenance to wife and children",
             "text": "Where a marriage is annulled, the court may order the husband to pay maintenance to the wife and children. The amount shall be determined based on the income and means of the parties."},
            {"section": "14", "title": "Cognizance of offence",
             "text": "No court inferior to a Metropolitan Magistrate or Judicial Magistrate of First Class shall try offences under this Act. Cognizance may be taken upon complaint by the Child Marriage Prohibition Officer, a relative, or any public servant."},
        ]
    },
    {
        "id": "guardian-wards-act",
        "title": "Guardians and Wards Act, 1890",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Guardians and Wards Act, 1890. Extends to whole of India. Came into force on 21st July 1890."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) guardian means a person having the care of the person of a minor or his property; (b) minor means a person who has not attained the age of majority (18 years); (c) ward means a minor for whose person or property or both a guardian has been appointed; (d) Court means the District Court or High Court having jurisdiction."},
            {"section": "4", "title": "Guardianship under natural law",
             "text": "Nothing in this Act shall be deemed to affect the jurisdiction of the Court to appoint or declare guardians of the persons of minors under any law for the time being in force. The natural guardian of a minor is the father, and after him, the mother."},
            {"section": "7", "title": "Powers of Court regarding guardianship",
             "text": "The Court may, on application, appoint a guardian for the person or property of a minor, or both. The Court shall consider: (a) the welfare of the minor; (b) the wishes of the minor's parents; (c) the suitability of the proposed guardian; (d) any other relevant factors."},
            {"section": "8", "title": "Court to regard welfare of minor",
             "text": "In appointing or declaring a guardian, the Court shall be guided by what, in the circumstances of the case, appears to be for the welfare of the minor. The welfare of the minor shall be the paramount consideration."},
            {"section": "9", "title": "Court to consider wishes of parents",
             "text": "The Court shall consider any wishes expressed by a deceased father or mother regarding the guardianship of their minor children. The Court may give effect to such wishes if it considers them to be for the welfare of the minor."},
            {"section": "10", "title": "Appointment by will or deed",
             "text": "A person entitled to appoint a guardian for his minor children may do so by will or deed. Such appointment shall take effect on the death of the appointer, subject to the approval of the Court."},
            {"section": "11", "title": "Guardianship by declaration",
             "text": "The Court may declare a person to be the guardian of a minor. The declaration shall have the same effect as an appointment under this Act."},
            {"section": "12", "title": "Powers of guardian",
             "text": "A guardian appointed under this Act shall have the power to: (a) take possession of the minor's property; (b) manage the minor's property; (c) represent the minor in legal proceedings; (d) do all other acts necessary for the welfare of the minor."},
            {"section": "14", "title": "Liability of guardian",
             "text": "A guardian shall be liable for: (a) loss to the minor's property due to his negligence or misconduct; (b) failure to maintain the minor; (c) failure to account for income and expenditure of the minor's property."},
            {"section": "17", "title": "Removal of guardian",
             "text": "The Court may remove a guardian if: (a) the guardian has neglected his duties; (b) the guardian has mismanaged the minor's property; (c) the guardian has become unsuitable; (d) the removal is for the welfare of the minor."},
            {"section": "19", "title": "Successor guardian",
             "text": "When a guardian dies, the Court may appoint a successor guardian. The Court shall consider the welfare of the minor and the wishes of the deceased guardian in making the appointment."},
        ]
    },
    {
        "id": "maintenance-parents-senior-citizens-act",
        "title": "Maintenance and Welfare of Parents and Senior Citizens Act, 2007",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Maintenance and Welfare of Parents and Senior Citizens Act, 2007. Extends to whole of India. Came into force on different dates in different States."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) parent includes father, mother, step-father, step-mother; (b) senior citizen means any person who has attained the age of 60 years; (c) maintenance includes provision for food, clothing, residence, medical attendance and treatment; (d) dependent means any child or relative who is dependent on the senior citizen."},
            {"section": "3", "title": "Maintenance of parents and senior citizens",
             "text": "A senior citizen who is unable to maintain himself from his own property or from the property of his children or relatives may apply to the Tribunal for an order directing his children or relatives to make a monthly allowance for his maintenance."},
            {"section": "4", "title": "Application for maintenance",
             "text": "An application for maintenance may be filed by: (a) a senior citizen; (b) any other person on behalf of a senior citizen; (c) the Tribunal on its own motion. The application shall be filed in the Tribunal having jurisdiction over the area where the senior citizen resides."},
            {"section": "5", "title": "Tribunal to make order",
             "text": "If the Tribunal is satisfied that the senior citizen is unable to maintain himself and that the children or relatives are able to provide maintenance, the Tribunal shall make an order directing the children or relatives to make a monthly allowance. The allowance shall not exceed Rs 10,000 per month."},
            {"section": "6", "title": "Factors to be considered",
             "text": "In determining the amount of maintenance, the Tribunal shall consider: (a) the income and property of the senior citizen; (b) the income and property of the children or relatives; (c) the needs of the senior citizen; (d) any other relevant factors."},
            {"section": "9", "title": "Transfer of property by senior citizen",
             "text": "Any transfer of property by a senior citizen to his children or relatives shall be voidable if the transfer was made under fraud, coercion or undue influence. The Tribunal may declare such transfer void."},
            {"section": "10", "title": "Right of senior citizen to withdraw maintenance",
             "text": "A senior citizen may apply to the Tribunal for withdrawal of maintenance order if circumstances change or if the children or relatives are unable to provide maintenance."},
            {"section": "13", "title": "Penalty for abandoning senior citizen",
             "text": "Any person who abandons a senior citizen in a hospital, old age home, or any other place shall be punished with imprisonment up to 3 months, or fine up to Rs 5,000, or both."},
            {"section": "14", "title": "Maintenance of old age homes",
             "text": "The Central Government and State Governments shall establish and maintain old age homes for senior citizens who are unable to maintain themselves. The old age homes shall provide food, clothing, shelter, medical care and recreational facilities."},
            {"section": "19", "title": "Appeal",
             "text": "Any person aggrieved by an order of the Tribunal may file an appeal before the District Court within 30 days of the order. The District Court may confirm, modify or set aside the order."},
        ]
    },
]

if __name__ == "__main__":
    print("Creating family & personal law acts...")
    for act in ACTS:
        create_act(act["id"], act["title"], act["sections"])
    print(f"Done: {len(ACTS)} acts created.")
