#!/usr/bin/env python3
"""Create missing practical guides for S3 KB."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from s3_upload import create_act

MODULES = [
    {
        "id": "practical-guides-3",
        "title": "Practical Legal Guides — Part 3",
        "sections": [
            {"section": "guide-1", "title": "How to Get a Legal Heir Certificate",
             "text": "A Legal Heir Certificate is needed to transfer property of a deceased person. Steps: (1) Apply to the Tehsildar or Sub-Divisional Magistrate of the area where the deceased last resided. (2) Submit Form 1 with death certificate, identity proof of applicant, and family tree. (3) The Tehsildar will issue a notice asking for objections from other legal heirs. (4) If no objections within 15 days, the certificate is issued. (5) The certificate is valid for property transfer, bank claims, insurance, and pension claims. (6) The process usually takes 15-30 days. (7) Fee: Rs 5-20 depending on the state. (8) If there are disputes, approach the Civil Court for a Succession Certificate."},
            {"section": "guide-2", "title": "How to Apply for a Succession Certificate",
             "text": "A Succession Certificate is issued by the Civil Court when there is no will or when the will is disputed. Steps: (1) File a petition under Section 372 of the Indian Succession Act in the District Court where the deceased last resided. (2) Submit death certificate, family tree, details of assets and liabilities, and details of legal heirs. (3) The court will issue a notice to all legal heirs. (4) The court will hear objections and determine the legal heirs. (5) The certificate authorizes the holder to collect debts, securities, and transfer property. (6) The process takes 3-6 months. (7) Fee: Court fee as per the value of the estate. (8) The certificate is binding on all parties."},
            {"section": "guide-3", "title": "How to Register a Company in India",
             "text": "Steps to register a Private Limited Company: (1) Obtain Digital Signature Certificate (DSC) for all directors. (2) Obtain Director Identification Number (DIN) for all directors. (3) Apply for name approval through RUN (Reserve Unique Name) on the MCA portal. (4) Prepare Memorandum of Association (MoA) and Articles of Association (AoA). (5) File incorporation documents (SPICe+ form) with the Registrar of Companies. (6) Pay the registration fee (Rs 5,000-15,000 depending on authorized capital). (7) The Registrar will verify documents and issue Certificate of Incorporation. (8) Apply for PAN and TAN. (9) Open a bank account. (10) Register for GST if turnover exceeds Rs 20 lakh. Timeline: 7-15 working days. Cost: Rs 10,000-25,000 including professional fees."},
            {"section": "guide-4", "title": "How to File Income Tax Return (ITR)",
             "text": "Steps to file Income Tax Return: (1) Collect Form 16 from employer, bank statements, and other income documents. (2) Login to the Income Tax e-filing portal (incometax.gov.in). (3) Select the appropriate ITR form (ITR-1 for salaried, ITR-2 for capital gains, ITR-3 for business income). (4) Fill in the return with income details, deductions, and tax paid. (5) Verify all details and click on 'Preview and Submit'. (6) Submit the return electronically. (7) Verify the return within 30 days using Aadhaar OTP, net banking, or by sending signed ITR-V to CPC Bengaluru. (8) Due date: July 31 for individuals, September 30 for audit cases. (9) If refund is due, it will be credited to your bank account. (10) E-filing is free for individuals."},
            {"section": "guide-5", "title": "How to File a Complaint with the National Human Rights Commission",
             "text": "Steps to file a complaint with NHRC: (1) File a complaint in writing addressed to the Secretary, NHRC, Manav Adhikar Bhawan, Block-C, GPO Complex, INA, New Delhi-110023. (2) The complaint must be in English or Hindi. (3) Include: name and address of complainant, name and address of the person whose rights were violated, details of the violation, when and where it occurred, and relief sought. (4) Send by post or submit in person. (5) Online complaint can be filed at nhrc.nic.in. (6) Complaint must be filed within one year of the incident. (7) The NHRC will register the complaint and investigate. (8) The NHRC may summon witnesses, inspect records, and recommend compensation. (9) The NHRC can recommend disciplinary action against public servants. (10) The NHRC's recommendations are not binding but are influential."},
            {"section": "guide-6", "title": "How to Apply for a Disability Certificate",
             "text": "Steps to obtain a Disability Certificate: (1) Visit the nearest Government Hospital or the District Medical Board. (2) Carry: Aadhaar card, address proof, passport-size photographs, and any medical records. (3) The hospital will conduct a medical examination. (4) A Medical Board of 3 doctors will assess the disability. (5) The Board will issue a certificate specifying the type and percentage of disability. (6) The certificate is valid for 5 years (permanent disability certificates may be valid for life). (7) The certificate can be used for: reservation in education and employment, tax benefits, travel concessions, and other welfare schemes. (8) Fee: Usually free in Government hospitals. (9) For 40% or more disability, the person is eligible for reservation under the RPWD Act, 2016. (10) Online registration is available in some states."},
            {"section": "guide-7", "title": "How to Obtain a Birth or Death Certificate",
             "text": "Steps to obtain Birth Certificate: (1) Within 21 days of birth, register with the local Registrar of Births and Deaths. (2) Submit: Form 1 (intimation of birth), hospital discharge summary, parents' ID proof. (3) The Registrar will issue the certificate. (4) Late registration (after 21 days but within 1 year): Fine of Rs 5-10. (5) After 1 year: Application to District Magistrate with affidavit. (6) Online registration available at some Municipal Corporation portals. Steps for Death Certificate: (1) Register within 21 days of death. (2) Submit: Form 2 (intimation of death), doctor's certificate, ID proof of deceased. (3) The Registrar will issue the certificate. (4) Late registration: Fine of Rs 5-10. (5) After 1 year: Application to District Magistrate. (6) Fee: Rs 5-50 depending on the state."},
            {"section": "guide-8", "title": "How to Apply for a Passport",
             "text": "Steps to apply for an Indian Passport: (1) Register on the Passport Seva portal (passportindia.gov.in). (2) Fill in the online application form (Form 1 for fresh passport). (3) Upload required documents: Aadhaar card, PAN card, birth certificate, address proof, and photographs. (4) Pay the fee online (Rs 1,500 for normal, Rs 3,500 for tatkal). (5) Schedule an appointment at the nearest Passport Seva Kendra (PSK). (6) Visit the PSK on the appointment date with original documents. (7) The PSK will verify documents and take biometrics. (8) Police verification will be conducted (usually within 21 days). (9) If verified, the passport will be dispatched within 7-10 working days. (10) Track application status on the portal. Timeline: 30-45 days (normal), 1-3 days (tatkal)."},
            {"section": "guide-9", "title": "How to File for Insolvency (Personal Bankruptcy)",
             "text": "Under the Insolvency and Bankruptcy Code, 2016: (1) A debtor (individual) may file an application before the Debt Recovery Tribunal. (2) The application must include: list of creditors, details of assets and liabilities, and a repayment proposal. (3) The Tribunal will appoint an insolvency professional to manage the debtor's affairs. (4) The creditors will vote on the repayment plan. (5) If 75% of creditors approve, the plan is binding on all creditors. (6) If the plan is not approved, the debtor's assets will be liquidated and distributed among creditors. (7) The debtor gets a discharge from remaining debts after liquidation. (8) The process takes 6-12 months. (9) The debtor must act in good faith and cooperate with the insolvency professional. (10) Personal insolvency is different from corporate insolvency."},
            {"section": "guide-10", "title": "How to File an Appeal Against a Government Order",
             "text": "Steps to file an appeal against a government order: (1) Identify the appeal provision in the relevant Act. Most Acts provide for appeal to a higher authority or tribunal. (2) File the appeal within the prescribed time limit (usually 30-90 days from the date of the order). (3) The appeal must be in writing and state the grounds of appeal. (4) Submit the appeal to the prescribed authority with the required fee. (5) The authority will hear both sides and decide the appeal. (6) If the appeal is dismissed, you may file a writ petition in the High Court under Article 226 of the Constitution. (7) The writ petition must be filed within 90 days of the appeal decision. (8) The High Court may quash the order, direct the authority to reconsider, or award compensation. (9) If the High Court decision is unsatisfactory, you may file an appeal in the Supreme Court under Article 136 (Special Leave Petition). (10) Legal aid is available for those who cannot afford a lawyer."},
        ]
    },
]

if __name__ == "__main__":
    print("Creating practical guides...")
    for mod in MODULES:
        create_act(mod["id"], mod["title"], mod["sections"])
    print(f"Done: {len(MODULES)} modules created.")
