#!/usr/bin/env python3
"""Upload Patents Act & Geographical Indications Act to S3."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from s3_upload import create_act

# ─── Patents Act, 1970 ───
create_act("patents-act", "The Patents Act, 1970", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Patents Act, 1970. It extends to the whole of India. It shall come into force on such date as the Central Government may, by notification in the Official Gazette, appoint."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'application' means an application for a patent; (b) 'controller' means the Controller General of Patents, Designs and Trade Marks; (c) 'invention' means a new product or process involving an inventive step and capable of industrial application; (d) 'patent' means a patent granted under this Act; (e) 'patentee' means the person for the time being entered on the register as the grantee or proprietor of a patent; (f) 'person interested' means a person engaged in, or in promoting, research in the same field as that to which the invention relates."},
    {"section": "3", "title": "What are not inventions",
     "text": "The following are not inventions within the meaning of this Act: (a) an invention which is frivolous or which claims anything obviously contrary to well established natural laws; (b) the mere discovery of a scientific principle or the mere discovery of any abstract theory or the mere discovery of any known phenomenon; (c) the mere discovery of a new form of a known substance which does not result in the enhancement of the known efficacy of that substance; (d) the mere admixture of two or more substances resulting in no new property; (e) the mere application of a known process to a known device; (f) a method of agriculture or horticulture; (g) a method of treatment of the human or animal body by surgery or therapy; (h) a plant or animal other than micro-organisms but including seeds, varieties and species; (i) a mathematical or business method; (j) a computer programme per se; (k) a literary, dramatic, musical or artistic work; (l) a mere scheme or mental act; (m) a mere presentation of information; (n) topography of integrated circuits; (o) an invention which, in view of the state of the art, is not capable of industrial application; (p) an invention the commercial exploitation of which is contrary to public order or morality."},
    {"section": "4", "title": "Inventions relating to atomic energy not patentable",
     "text": "No patent shall be granted in respect of an invention relating to atomic energy falling within the purview of the Atomic Energy Act, 1962."},
    {"section": "5", "title": "Inventions where only methods or processes of manufacture patentable",
     "text": "Only methods or processes of manufacture are patentable under this Act. No patents shall be granted for substances intended for use, or capable of being used, as food or medicine, or for any process of manufacture of such substance."},
    {"section": "6", "title": "Persons entitled to apply for patents",
     "text": "(1) Subject to the provisions of this Act, a patent may be granted to any person claiming to be the true and first inventor of the invention, or to the assignee of such person. (2) Where the invention is made by two or more persons jointly, they may apply jointly for a patent. (3) In the case of an invention made by an employee, the employer may be entitled to the patent in certain circumstances."},
    {"section": "7", "title": "Form of application",
     "text": "(1) Every application for a patent shall be in the prescribed form and shall be filed at the patent office. (2) The application shall contain a complete specification, which shall fully and particularly describe the invention and the manner in which it is to be performed. (3) The specification shall end with a claim or claims defining the scope of the invention."},
    {"section": "8", "title": "Complete specification",
     "text": "(1) The complete specification shall: (a) fully and particularly describe the invention and the manner in which it is to be performed; (b) disclose the best method of performing the invention known to the applicant; (c) be accompanied by drawings, if any; (d) contain claims defining the scope of the invention. (2) The claims shall be clear and concise and shall be supported by the description."},
    {"section": "9", "title": "Provisional specification",
     "text": "(1) Where an application is made with a provisional specification, a complete specification shall be filed within twelve months from the date of application. (2) If the complete specification is not filed within the said period, the application shall be deemed to be abandoned."},
    {"section": "10", "title": "Claims",
     "text": "(1) The claims shall define the scope of the invention and shall be clear and concise. (2) The claims shall be supported by the description and shall relate to one invention or a group of inventions. (3) The claims shall be construed in the light of the description and drawings."},
    {"section": "11", "title": "Priority date",
     "text": "The priority date of a claim shall be the date of filing of the application in respect of that claim, or if priority is claimed under the Paris Convention, the date of the earliest priority application."},
    {"section": "12", "title": "Examination of application",
     "text": "(1) Every application for a patent shall be examined by the controller to determine whether the invention is patentable. (2) The controller may require the applicant to furnish information relating to the prior art. (3) The controller may also conduct a search of prior art."},
    {"section": "13", "title": "Anticipation",
     "text": "An invention shall not be patentable if it was anticipated by publication in any document, or by public use or public knowledge in India or elsewhere before the priority date of the claim."},
    {"section": "14", "title": "Novelty",
     "text": "An invention is new if it does not form part of the state of the art, i.e., it has not been disclosed to the public anywhere in the world by publication, use, or otherwise before the priority date."},
    {"section": "15", "title": "Inventive step",
     "text": "An invention shall be deemed to involve an inventive step if it is not obvious to a person skilled in the art, having regard to the state of the art."},
    {"section": "16", "title": "Industrial application",
     "text": "An invention shall be deemed to be capable of industrial application if it can be made or used in any kind of industry."},
    {"section": "17", "title": "Opposition to grant of patent",
     "text": "(1) Any person may, within four months from the date of publication of the application, file a notice of opposition. (2) The opposition may be on the ground that the applicant is not entitled to the patent, or that the invention is not patentable, or that the complete specification does not sufficiently describe the invention."},
    {"section": "18", "title": "Grant of patent",
     "text": "(1) If the controller is satisfied that the application meets all the requirements, a patent shall be granted. (2) The patent shall be dated and sealed as of the date of the application. (3) The grant of a patent shall be published in the Official Gazette."},
    {"section": "19", "title": "Term of patent",
     "text": "The term of a patent shall be twenty years from the date of filing of the application, subject to the payment of renewal fees."},
    {"section": "20", "title": "Renewal fees",
     "text": "(1) Renewal fees shall be paid in respect of the third and every subsequent year of the patent. (2) The renewal fees may be paid within the prescribed time. (3) If the renewal fees are not paid, the patent shall cease to have effect."},
    {"section": "25", "title": "Registration of patent",
     "text": "(1) The controller shall maintain a register of patents. (2) The register shall contain the name and address of the patentee, the date of the patent, and any assignments or transfers. (3) The register shall be prima facie evidence of all matters entered therein."},
    {"section": "28", "title": "Rights of patentee",
     "text": "(1) Subject to the provisions of this Act, the patentee shall have the exclusive right to make, use, sell, and import the patented invention in India. (2) The patentee may assign or license the patent. (3) The patentee may also grant other rights in respect of the patent."},
    {"section": "30", "title": "Grant of licences",
     "text": "(1) The controller may grant licences under a patent in certain circumstances. (2) A licence may be granted where the patentee refuses to grant a licence on reasonable terms, or where the patent is not being worked in India."},
    {"section": "31", "title": "Compulsory licence",
     "text": "(1) Any person interested may apply to the controller for a compulsory licence on the ground that the reasonable requirements of the public have not been satisfied, or that the patented invention is not available at a reasonable price, or that the patented invention is not worked in India. (2) The controller may grant a compulsory licence on such terms as he thinks fit."},
    {"section": "32", "title": "Revocation of patent",
     "text": "(1) The controller may revoke a patent on the ground that the patentee is not entitled to the patent, or that the invention is not patentable, or that the complete specification does not sufficiently describe the invention. (2) A patent may also be revoked on the ground that the patentee has failed to pay the renewal fees."},
    {"section": "33", "title": "Surrender of patent",
     "text": "The patentee may surrender a patent by giving notice to the controller. The controller shall publish the notice and any person interested may within three months make representations to the controller."},
    {"section": "34", "title": "Assignment of patent",
     "text": "(1) A patent may be assigned wholly or in part. (2) The assignment shall be in writing and shall be registered with the controller. (3) The assignee shall have the same rights as the patentee."},
    {"section": "35", "title": "Patent of addition",
     "text": "(1) Where a patentee has made an improvement in or modification of an invention for which he already holds a patent, he may apply for a patent of addition. (2) A patent of addition shall not be granted before the grant of the original patent. (3) A patent of addition shall expire on the expiry of the original patent."},
    {"section": "40", "title": "Infringement of patent",
     "text": "(1) A patent shall be infringed by any person who, without the consent of the patentee, makes, uses, sells, or imports the patented invention. (2) The patentee may bring a suit for infringement in the appropriate court. (3) The court may grant an injunction, damages, or an account of profits."},
    {"section": "41", "title": "Defences to infringement",
     "text": "In an action for infringement, the defendant may plead: (a) that the patent is invalid; (b) that the defendant did not infringe the patent; (c) that the use of the invention was for experimental purposes; (d) that the invention was used for personal non-commercial use; (e) that the invention was used in the preparation of medicines."},
    {"section": "42", "title": "Power of controller to deal with applications",
     "text": "The controller may refuse to grant a patent, or may require the applicant to amend the application or specification, or may grant the patent subject to conditions."},
    {"section": "44", "title": "Register of patents",
     "text": "The controller shall maintain a register of patents, which shall be open to public inspection. The register shall contain particulars of all patents granted under this Act."},
    {"section": "45", "title": "Rectification of register",
     "text": "The controller may, on the application of any person interested, rectify the register by the insertion, omission, or correction of any entry."},
    {"section": "46", "title": "Restoration of lapsed patents",
     "text": "Where a patent has lapsed due to non-payment of renewal fees, the patentee may apply for restoration within eighteen months from the date of lapse."},
    {"section": "50", "title": "Powers of controller",
     "text": "The controller shall have the power to: (a) hear and decide applications for patents; (b) grant or refuse patents; (c) revoke or restore patents; (d) grant licences; (e) keep the register of patents; (f) do all other things necessary for the administration of this Act."},
    {"section": "51", "title": "Appeals",
     "text": "Any person aggrieved by a decision of the controller may appeal to the High Court within three months from the date of the decision."},
    {"section": "52", "title": "Penalties",
     "text": "Any person who: (a) falsely represents himself as a patentee; (b) makes false entries in the register; (c) fails to comply with an order of the controller, shall be punishable with imprisonment up to six months, or with fine, or with both."},
    {"section": "53", "title": "International applications",
     "text": "The Central Government may make rules for the filing of international applications under the Patent Cooperation Treaty. The provisions of this Act shall apply to such applications."},
    {"section": "54", "title": "Protection of secrets of state",
     "text": "No patent shall be granted for an invention which is relevant to defence or atomic energy, without the prior approval of the Central Government."},
])

# ─── Geographical Indications of Goods Act, 1999 ───
create_act("geographical-indications-act", "The Geographical Indications of Goods (Registration and Protection) Act, 1999", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Geographical Indications of Goods (Registration and Protection) Act, 1999. It extends to the whole of India and applies to geographical indications in respect of goods coming into India."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'geographical indication' means an indication which identifies such goods as originating from a particular region where a given quality, reputation or other characteristic is essentially attributable to its geographical origin; (b) 'goods' means any agricultural, natural or manufactured goods; (c) 'Controller' means the Controller General of Patents, Designs and Trade Marks; (d) 'prohibited acceptance' has the meaning assigned to it in section 9; (e) 'registered proprietor' means a person who is for the time being entered in the register as proprietor of a geographical indication; (f) 'registry' means the Geographical Indications Registry."},
    {"section": "3", "title": "Geographical Indications Registry",
     "text": "(1) There shall be established a Geographical Indications Registry at such place as the Central Government may specify. (2) The Registry shall be under the superintendence and direction of the Controller. (3) The Controller shall have the power to make rules for the administration of the Registry."},
    {"section": "4", "title": "Registration of geographical indications",
     "text": "(1) Any association of persons, or any producer or organisation established by or under any law, representing the interest of the producers of the concerned goods, may apply for the registration of a geographical indication. (2) The application shall be in the prescribed form and shall be accompanied by the prescribed fee. (3) The application shall specify the goods to which the geographical indication applies."},
    {"section": "5", "title": "Conditions for registration",
     "text": "A geographical indication shall be registered if: (a) it identifies the goods as originating from a particular region; (b) the quality, reputation or other characteristic of the goods is essentially attributable to its geographical origin; (c) the goods originate from the defined region; (d) the indication is not contrary to law or public policy."},
    {"section": "6", "title": "Prohibited acceptance",
     "text": "(1) A geographical indication shall not be registered if: (a) the indication is not a geographical indication; (b) the indication is not specific to a particular region; (c) the indication is contrary to law or public policy; (d) the indication is likely to mislead the public; (e) the indication contains or consists of matter which could be offensive to any class of persons. (2) A geographical indication which is identical with or similar to a trade mark shall not be registered."},
    {"section": "7", "title": "Application for registration",
     "text": "(1) An application for registration shall contain: (a) the name and address of the applicant; (b) the geographical indication; (c) the goods to which the geographical indication applies; (d) the description of the geographical area; (e) the specific quality, reputation or other characteristic of the goods; (f) such other particulars as may be prescribed. (2) The application shall be published in the Official Gazette."},
    {"section": "8", "title": "Opposition to registration",
     "text": "(1) Any person may, within three months from the date of publication, file a notice of opposition. (2) The opposition may be on the ground that the geographical indication does not comply with the requirements of this Act. (3) The Controller shall hear the parties and decide the opposition."},
    {"section": "9", "title": "Registration",
     "text": "(1) If no opposition is filed, or if the opposition is decided in favour of the applicant, the Controller shall register the geographical indication. (2) The registration shall be for a period of ten years from the date of registration, renewable for further periods of ten years each. (3) The registration shall be published in the Official Gazette."},
    {"section": "10", "title": "Duration and renewal of registration",
     "text": "(1) The registration of a geographical indication shall be for a period of ten years. (2) The registration may be renewed for further periods of ten years each on payment of the prescribed fee. (3) If the fee is not paid, the registration shall cease to have effect."},
    {"section": "11", "title": "Rights conferred by registration",
     "text": "(1) The registered proprietor of a geographical indication shall have the right to use the geographical indication in relation to the goods for which it is registered. (2) The registered proprietor may bring a suit for infringement against any person who uses a geographical indication which is identical with or similar to the registered geographical indication. (3) The registered proprietor may also bring a suit for passing off."},
    {"section": "12", "title": "Infringement of geographical indication",
     "text": "(1) A geographical indication is infringed by any person who: (a) uses a geographical indication which is identical with the registered geographical indication; (b) uses a geographical indication which is similar to the registered geographical indication; (c) uses a geographical indication which is likely to deceive or cause confusion; (d) uses a geographical indication in a manner which is likely to cause confusion. (2) The infringement may be in respect of the whole or any part of the goods."},
    {"section": "13", "title": "Actions for infringement",
     "text": "(1) The registered proprietor may bring a suit for infringement in the appropriate court. (2) The court may grant an injunction, damages, or an account of profits. (3) The court may also order the delivery up or destruction of the infringing goods."},
    {"section": "14", "title": "Defences to infringement",
     "text": "In an action for infringement, the defendant may plead: (a) that the geographical indication is not validly registered; (b) that the defendant's use does not constitute infringement; (c) that the use is in accordance with honest practices in industrial or commercial matters; (d) that the use is for the purpose of identifying the intended purpose of the goods; (e) that the use is for the purpose of comparative advertising."},
    {"section": "15", "title": "Registration of authorised users",
     "text": "(1) Any person who uses a geographical indication in the course of trade may apply to be registered as an authorised user. (2) The application shall be in the prescribed form and shall be accompanied by the prescribed fee. (3) The Controller shall register the authorised user and enter his name in the register."},
    {"section": "16", "title": "Use of geographical indication by authorised users",
     "text": "An authorised user shall have the right to use the geographical indication in relation to the goods for which he is registered, subject to the conditions of registration."},
    {"section": "17", "title": "Assignment and transmission",
     "text": "(1) A geographical indication may be assigned or transmitted with or without the goodwill of the business. (2) The assignment or transmission shall be in writing and shall be registered with the Controller. (3) The Controller may refuse to register the assignment or transmission if it is likely to deceive or cause confusion."},
    {"section": "18", "title": "Surrender",
     "text": "The registered proprietor may surrender a geographical indication by giving notice to the Controller. The Controller shall publish the notice and any person interested may within three months make representations."},
    {"section": "19", "title": "Removal from register",
     "text": "(1) The Controller may, on the application of any person interested, remove a geographical indication from the register on the ground that: (a) the geographical indication was registered without sufficient cause; (b) the geographical indication is likely to deceive or cause confusion; (c) the geographical indication has not been used for a continuous period of five years. (2) The Controller shall hear the parties before making any order."},
    {"section": "20", "title": "Rectification of register",
     "text": "The Controller may, on the application of any person interested, rectify the register by the insertion, omission, or correction of any entry."},
    {"section": "21", "title": "Powers of Controller",
     "text": "The Controller shall have the power to: (a) hear and decide applications for registration; (b) register or refuse registration; (c) register authorised users; (d) keep the register; (e) do all other things necessary for the administration of this Act."},
    {"section": "22", "title": "Appeals",
     "text": "Any person aggrieved by a decision of the Controller may appeal to the High Court within three months from the date of the decision."},
    {"section": "23", "title": "Penalties",
     "text": "Any person who: (a) uses a geographical indication which is not registered; (b) falsifies a geographical indication; (c) makes false entries in the register, shall be punishable with imprisonment up to three years, or with fine, or with both."},
    {"section": "24", "title": "Offences by companies",
     "text": "Where an offence under this Act is committed by a company, every person who, at the time the offence was committed, was in charge of and was responsible for the conduct of the business shall be deemed to be guilty of the offence."},
    {"section": "25", "title": "Application to existing geographical indications",
     "text": "The provisions of this Act shall apply to geographical indications which are in use before the commencement of this Act, subject to such adaptations and modifications as may be prescribed."},
    {"section": "26", "title": "Protection of trade marks",
     "text": "Nothing in this Act shall affect the right of a proprietor of a trade mark to use his trade mark in relation to goods for which the trade mark is registered."},
    {"section": "27", "title": "Power of Central Government",
     "text": "The Central Government may make rules for carrying out the provisions of this Act. Such rules may provide for all matters which are required to be prescribed under this Act."},
    {"section": "28", "title": "International obligations",
     "text": "The provisions of this Act shall apply to geographical indications which are protected under international agreements to which India is a party."},
])

print("Done: patents-act, geographical-indications-act")
