#!/usr/bin/env python3
"""Upload RBI Act & IRDAI Act to S3."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from s3_upload import create_act

# ─── Reserve Bank of India Act, 1934 ───
create_act("rbi-act", "The Reserve Bank of India Act, 1934", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Reserve Bank of India Act, 1934. It extends to the whole of India. It shall come into force on such date as the Central Government may, by notification in the Official Gazette, appoint."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'Bank' means the Reserve Bank of India established under section 3; (b) 'Board' means the Central Board of the Bank; (c) 'Central Government' means the Government of India; (d) 'demand liabilities' means all liabilities of the Bank which are payable on demand; (e) 'note' means a bank note issued by the Bank; (f) 'rupee coin' means a coin of Government of India; (g) 'scheduled bank' means a bank included in the Second Schedule."},
    {"section": "3", "title": "Establishment of the Reserve Bank of India",
     "text": "(1) There shall be established a bank to be called the Reserve Bank of India. (2) The Bank shall be a body corporate with perpetual succession and a common seal. (3) The Bank shall have power to acquire and dispose of property, and to enter into contracts. (4) The Bank may sue and be sued in its corporate name."},
    {"section": "4", "title": "Central Office",
     "text": "The Central Office of the Bank shall be at Bombay. The Bank may establish branches or offices at any place in India."},
    {"section": "5", "title": "Capital of the Bank",
     "text": "(1) The authorised capital of the Bank shall be five crore rupees divided into shares of one hundred rupees each. (2) The issued capital of the Bank shall be held by the Central Government. (3) The Bank may increase its capital with the previous sanction of the Central Government."},
    {"section": "7", "title": "Management",
     "text": "(1) The management of the Bank shall vest in the Central Board. (2) The Central Board shall consist of a Governor and such number of Deputy Governors and other directors as may be prescribed. (3) The Governor and Deputy Governors shall be appointed by the Central Government. (4) The other directors shall be nominated by the Central Government."},
    {"section": "8", "title": "Governor and Deputy Governors",
     "text": "(1) The Governor shall be appointed by the Central Government for a term of four years. (2) The Deputy Governors shall be appointed for a term of five years. (3) The Governor and Deputy Governors shall be whole-time officers of the Bank. (4) The Governor shall be the chairman of the Central Board."},
    {"section": "9", "title": "Functions of the Bank",
     "text": "The Bank shall: (a) regulate the issue of bank notes; (b) maintain the reserves; (c) act as banker to the Central Government; (d) act as banker's bank; (e) manage the public debt; (f) promote monetary stability; (g) regulate the financial system; (h) perform such other functions as may be assigned to it by the Central Government."},
    {"section": "10", "title": "General superintendence and direction",
     "text": "The general superintendence and direction of the affairs of the Bank shall be vested in the Central Board, which may exercise all such powers and do all such things as may be exercised or done by the Bank."},
    {"section": "11", "title": "Local Boards",
     "text": "(1) There may be established Local Boards at Bombay, Calcutta, Madras and such other places as the Central Board may determine. (2) The Local Boards shall advise the Central Board on such matters as may be referred to them. (3) The Local Boards shall exercise such powers as may be delegated to them."},
    {"section": "12", "title": "Committees of the Board",
     "text": "The Central Board may appoint committees for specific purposes. The committees may exercise such powers as may be delegated to them by the Central Board."},
    {"section": "13", "title": "Delegation of powers",
     "text": "The Central Board may, by resolution, delegate any of its powers to the Governor, any Deputy Governor, or any officer of the Bank, subject to such conditions as it may think fit."},
    {"section": "17", "title": "Power to issue bank notes",
     "text": "(1) The Bank shall have the sole right to issue bank notes in India. (2) The Bank may issue notes of the denomination of two rupees and above. (3) The Bank shall maintain against its notes issued a reserve of not less than two hundred rupees in gold coin or bullion or foreign securities."},
    {"section": "18", "title": "Bank notes",
     "text": "(1) Every bank note shall be legal tender in India. (2) The bank notes shall be in the prescribed form and shall bear the signatures of the Governor and the officers of the Bank. (3) The Bank may withdraw any bank note from circulation."},
    {"section": "19", "title": "Reserve fund",
     "text": "(1) The Bank shall maintain a reserve fund of not less than five crore rupees. (2) The reserve fund shall be invested in securities of the Central Government or of any State Government. (3) The Bank may add to the reserve fund from its profits."},
    {"section": "20", "title": "Cash reserve",
     "text": "Every scheduled bank shall maintain with the Bank a cash reserve of not less than three per cent of its demand liabilities and ten per cent of its time liabilities, or such other rates as may be specified by the Bank."},
    {"section": "21", "title": "Cash reserve ratio",
     "text": "(1) The Bank may, by notification, specify the cash reserve ratio to be maintained by scheduled banks. (2) The cash reserve ratio shall be in addition to any other reserve required under this Act. (3) The Bank may vary the cash reserve ratio from time to time."},
    {"section": "21A", "title": "Statutory liquidity ratio",
     "text": "(1) Every scheduled bank shall maintain with itself a statutory liquidity ratio of not less than twenty per cent of its demand and time liabilities. (2) The Bank may, by notification, specify the statutory liquidity ratio. (3) The statutory liquidity ratio shall be in addition to the cash reserve ratio."},
    {"section": "22", "title": "Power to give directions",
     "text": "(1) The Bank may give directions to any scheduled bank or any class of scheduled banks on matters relating to banking policy. (2) The directions may relate to interest rates, advances, reserves, or any other matter. (3) Every scheduled bank shall be bound by such directions."},
    {"section": "23", "title": "Power to inspect banks",
     "text": "(1) The Bank may inspect the books of any scheduled bank. (2) The Bank may call for information and returns from any scheduled bank. (3) The Bank may give directions for the rectification of any irregularity found in the course of inspection."},
    {"section": "24", "title": "Power to control advances",
     "text": "(1) The Bank may, by general or special order, direct any scheduled bank to make advances to any particular sector or industry. (2) The Bank may also prescribe the terms and conditions of such advances. (3) Every scheduled bank shall comply with such directions."},
    {"section": "25", "title": "Protection of depositors",
     "text": "(1) The Bank may take such measures as it considers necessary for the protection of depositors. (2) The Bank may issue directions to any scheduled bank for the protection of depositors. (3) The Bank may also require any scheduled bank to furnish information relating to its deposits."},
    {"section": "26", "title": "Banker to the Central Government",
     "text": "(1) The Bank shall be the banker to the Central Government. (2) The Bank may act as banker to any State Government. (3) The Bank shall maintain the accounts of the Central Government and shall make payments and receipts on its behalf."},
    {"section": "27", "title": "Public debt office",
     "text": "The Bank shall maintain a public debt office for the management of the public debt of the Central Government. The public debt office shall carry out such functions as may be assigned to it by the Central Government."},
    {"section": "28", "title": "Promotion of monetary stability",
     "text": "It is the primary objective of the Bank to promote monetary stability and a sound financial system in India. The Bank shall also support the economic policies of the Central Government."},
    {"section": "29", "title": "Regulation of foreign exchange",
     "text": "(1) The Bank may regulate the purchase and sale of foreign exchange. (2) The Bank may prescribe the rates of exchange for the purchase and sale of foreign currency. (3) The Bank may also regulate the import and export of foreign currency."},
    {"section": "30", "title": "Regulation of money market",
     "text": "(1) The Bank may regulate the money market. (2) The Bank may issue guidelines for the functioning of the money market. (3) The Bank may also regulate the functioning of non-banking financial companies in the money market."},
    {"section": "31", "title": "Penalties",
     "text": "Any person who: (a) contravenes any provision of this Act; (b) fails to comply with any direction of the Bank; (c) furnishes false information to the Bank, shall be punishable with fine which may extend to ten thousand rupees, and in the case of a continuing offence, with an additional fine which may extend to five hundred rupees per day."},
    {"section": "32", "title": "Offences by companies",
     "text": "Where an offence under this Act is committed by a company, every person who, at the time the offence was committed, was in charge of and was responsible for the conduct of the business shall be deemed to be guilty of the offence."},
    {"section": "33", "title": "Power of Central Government",
     "text": "The Central Government may give directions to the Bank on matters of policy, after consultation with the Governor. The Bank shall comply with such directions."},
    {"section": "34", "title": "Indemnity",
     "text": "No suit or other legal proceeding shall lie against the Bank or any officer of the Bank for anything done or intended to be done in good faith under this Act."},
])

# ─── Insurance Regulatory and Development Authority of India Act, 1999 ───
create_act("irdai-act", "The Insurance Regulatory and Development Authority of India Act, 1999", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Insurance Regulatory and Development Authority of India Act, 1999. It extends to the whole of India. It shall come into force on such date as the Central Government may, by notification in the Official Gazette, appoint."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'Authority' means the Insurance Regulatory and Development Authority of India established under section 3; (b) 'Chairperson' means the Chairperson of the Authority; (c) 'insurance company' means a company registered under the Companies Act, 2013 and engaged in the business of insurance; (d) 'insurable interest' means an interest in the subject matter of insurance; (e) 'insurance business' means the business of effecting contracts of insurance; (f) 'life insurance business' means the business of effecting contracts of insurance on human life."},
    {"section": "3", "title": "Establishment of the Authority",
     "text": "(1) There shall be established an Authority to be called the Insurance Regulatory and Development Authority of India. (2) The Authority shall be a body corporate with perpetual succession and a common seal. (3) The Authority shall have power to acquire and dispose of property, and to enter into contracts. (4) The Authority may sue and be sued in its corporate name."},
    {"section": "4", "title": "Composition of the Authority",
     "text": "(1) The Authority shall consist of a Chairperson and such number of members as may be prescribed. (2) The Chairperson and members shall be appointed by the Central Government. (3) The Chairperson and members shall be whole-time officers of the Authority. (4) The Chairperson and members shall hold office for a term of five years."},
    {"section": "5", "title": "Qualifications of Chairperson and members",
     "text": "The Chairperson and members shall be persons of ability, integrity and standing who have demonstrated capability and standing in the fields of insurance, finance, law, economics, actuarial science, or any other discipline relevant to the regulation of insurance."},
    {"section": "6", "title": "Functions of the Authority",
     "text": "The Authority shall: (a) regulate the insurance industry; (b) protect the interests of policyholders; (c) promote the development of the insurance industry; (d) ensure the financial soundness of insurance companies; (e) regulate the registration of insurance companies; (f) regulate the conduct of insurance business; (g) promote and regulate professional organisations connected with the insurance industry; (h) perform such other functions as may be assigned to it by the Central Government."},
    {"section": "7", "title": "Powers of the Authority",
     "text": "The Authority shall have the power to: (a) issue directions to insurance companies; (b) call for information and returns from insurance companies; (c) inspect the books of insurance companies; (d) conduct investigations and inquiries; (e) impose penalties for contravention of this Act or rules made thereunder; (f) approve the terms and conditions of insurance policies; (g) regulate the investment of funds by insurance companies; (h) regulate the commission and expenses of insurance companies."},
    {"section": "8", "title": "Registration of insurance companies",
     "text": "(1) No person shall carry on insurance business in India without obtaining a certificate of registration from the Authority. (2) The application for registration shall be in the prescribed form and shall be accompanied by the prescribed fee. (3) The Authority may grant or refuse registration after considering the application."},
    {"section": "9", "title": "Conditions for registration",
     "text": "(1) The Authority may grant registration to an insurance company if: (a) the company is registered under the Companies Act, 2013; (b) the company has the prescribed minimum capital; (c) the company has the prescribed solvency margin; (d) the company has the prescribed net worth; (e) the company has the prescribed management and infrastructure; (f) the company satisfies such other conditions as may be prescribed. (2) The registration shall be subject to such conditions as may be specified by the Authority."},
    {"section": "10", "title": "Certificate of registration",
     "text": "(1) The certificate of registration shall be in the prescribed form. (2) The certificate of registration shall specify the class or classes of insurance business which the company may carry on. (3) The certificate of registration may be suspended or cancelled by the Authority for contravention of this Act or rules made thereunder."},
    {"section": "11", "title": "Solvency margin",
     "text": "(1) Every insurance company shall maintain the prescribed solvency margin at all times. (2) The solvency margin shall be calculated in the prescribed manner. (3) The Authority may require any insurance company to increase its solvency margin if it considers it necessary."},
    {"section": "12", "title": "Investment of funds",
     "text": "(1) Every insurance company shall invest its funds in accordance with the prescribed investment guidelines. (2) The investment guidelines may prescribe the types of investments, the limits on investments, and the conditions for investments. (3) The Authority may vary the investment guidelines from time to time."},
    {"section": "13", "title": "Valuation of assets and liabilities",
     "text": "(1) Every insurance company shall prepare a valuation report in the prescribed manner. (2) The valuation report shall be submitted to the Authority within the prescribed time. (3) The Authority may require any insurance company to get its valuation report audited by an approved valuer."},
    {"section": "14", "title": "Filing of tariffs",
     "text": "(1) Every insurance company shall file its tariffs with the Authority. (2) The tariffs shall specify the rates, terms and conditions of insurance. (3) The Authority may approve or reject the tariffs after considering the same."},
    {"section": "15", "title": "Commission and expenses",
     "text": "(1) The Authority may prescribe the maximum commission and expenses which an insurance company may incur. (2) The commission and expenses shall be in proportion to the premium collected. (3) The Authority may vary the maximum commission and expenses from time to time."},
    {"section": "16", "title": "Protection of policyholders",
     "text": "(1) The Authority shall take all measures for the protection of policyholders. (2) The Authority may issue directions to insurance companies for the protection of policyholders. (3) The Authority may also require insurance companies to furnish information relating to their policies and claims."},
    {"section": "17", "title": "Claims settlement",
     "text": "(1) Every insurance company shall settle claims within the prescribed time. (2) The Authority may issue guidelines for the settlement of claims. (3) The Authority may also take action against insurance companies which fail to settle claims within the prescribed time."},
    {"section": "18", "title": "Grievance redressal",
     "text": "(1) The Authority shall establish a grievance redressal mechanism for policyholders. (2) The Authority may also establish an ombudsman for the resolution of disputes. (3) The Authority may issue guidelines for the redressal of grievances."},
    {"section": "19", "title": "Reinsurance",
     "text": "(1) Every insurance company shall cede a portion of its risk to reinsurers in accordance with the prescribed reinsurance guidelines. (2) The reinsurance guidelines may prescribe the ceding limits, the types of reinsurers, and the terms of reinsurance. (3) The Authority may vary the reinsurance guidelines from time to time."},
    {"section": "20", "title": "Takaful insurance",
     "text": "(1) The Authority may regulate Takaful insurance or Islamic insurance. (2) The Authority may issue guidelines for the functioning of Takaful insurance. (3) The guidelines may prescribe the principles, the structure, and the operations of Takaful insurance."},
    {"section": "21", "title": "Micro insurance",
     "text": "(1) The Authority may regulate micro insurance. (2) The Authority may issue guidelines for the promotion and regulation of micro insurance. (3) The guidelines may prescribe the eligibility, the coverage, and the premium for micro insurance."},
    {"section": "22", "title": "Penalties",
     "text": "Any person who: (a) carries on insurance business without registration; (b) contravenes any provision of this Act; (c) fails to comply with any direction of the Authority; (d) furnishes false information to the Authority, shall be punishable with fine which may extend to one crore rupees, and in the case of a continuing offence, with an additional fine which may extend to ten lakh rupees per day."},
    {"section": "23", "title": "Power to make rules",
     "text": "(1) The Central Government may, by notification, make rules for carrying out the provisions of this Act. (2) Such rules may provide for all matters which are required to be prescribed under this Act. (3) The rules shall be laid before each House of Parliament."},
    {"section": "24", "title": "Power to make regulations",
     "text": "(1) The Authority may, by notification, make regulations for carrying out the provisions of this Act. (2) Such regulations may provide for all matters which are required to be prescribed by the Authority. (3) The regulations shall be laid before each House of Parliament."},
    {"section": "25", "title": "Application of Companies Act",
     "text": "The provisions of the Companies Act, 2013 shall apply to insurance companies insofar as they are not inconsistent with the provisions of this Act."},
    {"section": "26", "title": "Indemnity",
     "text": "No suit or other legal proceeding shall lie against the Authority or any officer of the Authority for anything done or intended to be done in good faith under this Act."},
])

print("Done: rbi-act, irdai-act")
