#!/usr/bin/env python3
"""Create missing commercial & financial acts for S3 KB."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from s3_upload import create_act

ACTS = [
    {
        "id": "competition-act",
        "title": "Competition Act, 2002",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Competition Act, 2002. Extends to whole of India. Sections 1-16 came into force on 20th May 2003; remaining sections on 1st June 2009."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) agreement includes any arrangement or understanding or action in concert; (b) cartel means an association of producers, sellers, distributors, traders or service providers who limit production, distribution, sale or price; (c) combination means acquisition of control, merger or amalgamation; (d) Commission means the Competition Commission of India established under section 7."},
            {"section": "3", "title": "Anti-competitive agreements",
             "text": "No enterprise shall enter into any agreement which causes or is likely to cause an appreciable adverse effect on competition within India. Agreements that directly or indirectly determine prices, limit production, share markets, or involve bid rigging are presumed to have anti-competitive effects. Penalties: up to 10% of average turnover for last 3 financial years."},
            {"section": "4", "title": "Abuse of dominant position",
             "text": "No enterprise shall abuse its dominant position. Dominance exists when an enterprise enjoys a position of strength to operate independently of competitive forces. Abuse includes imposing unfair conditions, limiting production, denying market access, and leveraging dominance. Penalties: up to 10% of average turnover for last 3 years."},
            {"section": "5", "title": "Regulation of combinations",
             "text": "No person shall enter into a combination which causes or is likely to cause an appreciable adverse effect on competition. Threshold limits for notification are based on assets and turnover of the parties and the combined entity."},
            {"section": "6", "title": "Notification of combinations",
             "text": "Parties to a combination exceeding threshold limits shall notify the Commission within 30 days of board approval. Failure to notify: penalty up to 1% of combined turnover or assets, whichever is higher."},
            {"section": "7", "title": "Establishment of Commission",
             "text": "The Central Government shall establish the Competition Commission of India with a Chairperson and 2-6 members. The Commission shall be a body corporate with perpetual succession."},
            {"section": "17", "title": "Duties of Commission",
             "text": "The Commission shall: eliminate practices having adverse effect on competition, promote and sustain competition, protect consumer interests, and ensure freedom of trade by participants in markets in India."},
            {"section": "27", "title": "Orders for anti-competitive agreements",
             "text": "If contravention of section 3 is found, the Commission may: (a) direct cease and desist; (b) impose penalty up to 10% of average turnover; (c) modify the agreement; (d) pass such other order as it deems fit."},
            {"section": "28", "title": "Orders for abuse of dominant position",
             "text": "If contravention of section 4 is found, the Commission may: cease and desist, impose penalty up to 10% of average turnover, direct division of the dominant enterprise, or pass other appropriate orders."},
            {"section": "34", "title": "Orders for combinations",
             "text": "After hearing parties, the Commission may approve the combination with modifications, or disapprove it if it causes appreciable adverse effect on competition. Conditions may be imposed on parties."},
            {"section": "42", "title": "Penalty for non-compliance",
             "text": "Failure to comply with Commission orders: penalty up to Rs 1 lakh per day of non-compliance, subject to maximum of Rs 10 crore."},
        ]
    },
    {
        "id": "sebi-act",
        "title": "Securities and Exchange Board of India Act, 1992",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Securities and Exchange Board of India Act, 1992. Extends to whole of India. Came into force on 30th January 1992."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) Board means SEBI established under section 3; (b) securities has the meaning in section 2(h) of the Securities Contracts (Regulation) Act, 1956; (c) stock exchange means any body of individuals constituted for regulating the business of buying, selling or dealing in securities."},
            {"section": "3", "title": "Establishment of SEBI",
             "text": "The Central Government shall establish the Securities and Exchange Board of India to protect investor interests, promote development of, and regulate the securities market. SEBI is a body corporate with perpetual succession and common seal."},
            {"section": "4", "title": "Composition",
             "text": "SEBI shall consist of: (a) a Chairman appointed by the Central Government; (b) 2 members from officers of the Central Government; (c) 1 member from officers of the Reserve Bank of India; (d) 5 members appointed by the Central Government, of whom at least 3 shall be whole-time members."},
            {"section": "10", "title": "Functions of SEBI",
             "text": "SEBI shall protect investor interests and regulate the securities market by: (a) regulating business in securities; (b) registering and regulating stock brokers, sub-brokers, share transfer agents, bankers to an issue, registrars, underwriters, portfolio managers, investment advisors; (c) registering and regulating depositories, participants, custodians, clearing houses; (d) promoting code of conduct for intermediaries."},
            {"section": "11", "title": "Powers of SEBI",
             "text": "SEBI may: (a) call for information from any person relating to the securities market; (b) inspect books of accounts and records of any person; (c) issue directions including cease and desist orders; (d) impose penalties as prescribed."},
            {"section": "11A", "title": "Registration of intermediaries",
             "text": "No person shall act as an intermediary or operate in the securities market without obtaining a certificate of registration from SEBI. SEBI may grant, revoke or suspend registration subject to conditions."},
            {"section": "11B", "title": "Power to issue directions",
             "text": "If SEBI is satisfied that securities are being dealt in a manner prejudicial to investors or market, it may by order direct any person to: (a) cease and desist from certain dealings; (b) not to dispose of securities; (c) refund amounts collected from investors; (d) comply with such other directions as it deems fit."},
            {"section": "12", "title": "Powers of search and seizure",
             "text": "SEBI may authorise any of its officers to enter any place, search and seize books of accounts, documents or records relevant to an investigation. Seized materials must be returned within 30 days if no proceedings are initiated."},
            {"section": "15A", "title": "Penalty for failure to furnish information",
             "text": "Failure to furnish information called for by SEBI: penalty up to Rs 1 lakh for each day of failure, subject to maximum of Rs 1 crore."},
            {"section": "15B", "title": "Penalty for failure to enter into agreement",
             "text": "Failure to enter into written agreement as required: penalty up to Rs 1 lakh for each day of failure, subject to maximum of Rs 1 crore."},
            {"section": "15C", "title": "Penalty for failure to desist",
             "text": "Failure to comply with SEBI's cease and desist order: penalty up to Rs 1 lakh for each day of failure, subject to maximum of Rs 1 crore."},
            {"section": "21", "title": "Establishment of Securities Appellate Tribunal",
             "text": "The Central Government shall establish one or more Securities Appellate Tribunals to hear appeals against SEBI orders. The Tribunal shall consist of a Presiding Officer and 2 members."},
        ]
    },
    {
        "id": "fema-act",
        "title": "Foreign Exchange Management Act, 1999",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Foreign Exchange Management Act, 1999. Extends to whole of India. Came into force on 1st June 2000."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) authorised person means an authorised dealer, money changer, offshore banking unit or any other person authorised by the Reserve Bank; (b) capital account transaction means a transaction which alters the assets or liabilities of a person outside India; (c) current account transaction means any transaction other than capital account transaction; (d) foreign exchange means foreign currency, deposits, credits and balances denominated in foreign currency."},
            {"section": "3", "title": "Dealing in foreign exchange",
             "text": "No person shall deal in or transfer any foreign exchange or foreign security to any person not being an authorised person. No person shall acquire, hold, own, possess or transfer any foreign exchange, foreign security or any immovable property situated outside India except as permitted under this Act."},
            {"section": "4", "title": "Holding of foreign exchange",
             "text": "No person resident in India shall acquire, hold, own, possess or transfer any foreign exchange, foreign security or immovable property situated outside India, except as provided under this Act or rules/regulations made thereunder."},
            {"section": "5", "title": "Current account transactions",
             "text": "Any person may sell or draw foreign exchange to or from an authorised person for any current account transaction, subject to the general or special directions of the Reserve Bank. The Central Government may restrict current account transactions by notification."},
            {"section": "6", "title": "Capital account transactions",
             "text": "The Reserve Bank may regulate capital account transactions by regulations. Any person may sell or draw foreign exchange for capital account transactions as permitted by the Reserve Bank. The RBI may prohibit, restrict or regulate capital account transactions."},
            {"section": "7", "title": "Export of goods and services",
             "text": "Every person exporting goods or services shall make a declaration of the value and method of realisation in the prescribed form. The proceeds of export must be realised and repatriated to India within the prescribed period."},
            {"section": "10", "title": "Power of Reserve Bank to issue directions",
             "text": "The Reserve Bank may, for the purpose of securing compliance with this Act, issue directions to authorised persons relating to: (a) any transaction in foreign exchange; (b) any payment to be made from or to any person outside India; (c) any capital account transaction."},
            {"section": "13", "title": "Contravention of provisions",
             "text": "Any person who contravenes any provision of this Act or any rule, regulation or direction made thereunder shall be liable to a penalty up to three times the sum involved in such contravention, or up to Rs 2 lakh where the amount is not quantifiable. In continuing contravention, additional penalty up to Rs 5,000 per day."},
            {"section": "16", "title": "Adjudication",
             "text": "The Reserve Bank or the Central Government may appoint an adjudicating authority to adjudicate penalties under this Act. The authority shall give an opportunity of being heard before passing any order."},
            {"section": "18", "title": "Special Director (Enforcement)",
             "text": "The Central Government may appoint a Special Director (Enforcement) to exercise powers of search, seizure and arrest under this Act. The Special Director shall have the powers of a civil court."},
            {"section": "19", "title": "Power of search and seizure",
             "text": "The Special Director or any officer authorised by the Reserve Bank may search any place, seize documents, foreign exchange or securities found during search. Seized materials must be produced before the Special Director within 48 hours."},
            {"section": "37", "title": "Appellate Tribunal",
             "text": "The Central Government shall establish an Appellate Tribunal for hearing appeals against orders of the adjudicating authority. The Tribunal shall consist of a Chairperson and members as prescribed."},
        ]
    },
    {
        "id": "fema-non-pci-act",
        "title": "Foreign Contribution (Regulation) Act, 2010",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Foreign Contribution (Regulation) Act, 2010. Extends to whole of India. Came into force on 1st May 2011."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) foreign contribution means the donation, delivery or transfer of any article, currency or security by a foreign source; (b) foreign source includes any foreign government, foreign association, foreign company, citizen of a foreign country; (c) association means an association of individuals, whether incorporated or not."},
            {"section": "3", "title": "Regulation of foreign contribution",
             "text": "No person having a definite cultural, economic, educational, religious or social programme shall accept or utilise foreign contribution without obtaining a certificate of registration from the Central Government."},
            {"section": "4", "title": "Prohibition of foreign contribution for certain activities",
             "text": "No person shall accept or utilise any foreign contribution for: (a) activities detrimental to national interest; (b) activities likely to affect public interest; (c) political purposes; (d) any activity not consistent with the aims and objects of the recipient."},
            {"section": "6", "title": "Registration of associations",
             "text": "Every association desiring to receive foreign contribution shall make an application to the Central Government for registration. The Government may grant registration subject to conditions, or refuse registration with reasons."},
            {"section": "7", "title": "Certification of registration",
             "text": "Upon registration, the association shall be permitted to receive foreign contribution and shall utilise the same only for the purposes for which it was received. The registration is valid for 5 years and may be renewed."},
            {"section": "8", "title": "Power to suspend or cancel registration",
             "text": "The Central Government may suspend or cancel the certificate of registration if: (a) the association has violated any provision of this Act; (b) the registration was obtained by fraud; (c) the association has ceased to exist; (d) the association is misusing foreign contribution."},
            {"section": "16", "title": "Manner of receiving foreign contribution",
             "text": "Foreign contribution shall be received only through a single bank account designated for the purpose, with a scheduled bank approved by the Reserve Bank of India. All foreign contributions must be deposited in this account."},
            {"section": "17", "title": "Utilisation of foreign contribution",
             "text": "Foreign contribution shall be utilised only for the purposes for which it was received and in accordance with the terms and conditions of the certificate of registration. No portion of the foreign contribution shall be transferred to any other association or person."},
            {"section": "21", "title": "Power of Government to prohibit receipt of foreign contribution",
             "text": "The Central Government may, by order, prohibit any association from receiving foreign contribution if it is satisfied that such receipt is prejudicial to: (a) the security of the State; (b) public interest; (c) freedom of speech; (d) integrity of the nation."},
            {"section": "29", "title": "Penalty for contravention",
             "text": "Any person who contravenes any provision of this Act shall be punished with imprisonment up to 5 years, or fine up to Rs 5 lakh, or both. For subsequent contravention: imprisonment up to 10 years."},
            {"section": "31", "title": "Offence by companies",
             "text": "Where an offence under this Act has been committed by a company, every person who was in charge of and responsible for the company's conduct shall be deemed guilty. The company shall also be punished with fine up to Rs 10 lakh."},
        ]
    },
    {
        "id": "msme-act",
        "title": "Micro, Small and Medium Enterprises Development Act, 2006",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Micro, Small and Medium Enterprises Development Act, 2006. Extends to whole of India. Came into force on 2nd October 2006."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) micro enterprise means an enterprise where investment in plant and machinery does not exceed Rs 1 crore and turnover does not exceed Rs 5 crore; (b) small enterprise means investment up to Rs 10 crore and turnover up to Rs 50 crore; (c) medium enterprise means investment up to Rs 50 crore and turnover up to Rs 250 crore; (d) enterprise means an industrial undertaking or business concern."},
            {"section": "3", "title": "Classification of enterprises",
             "text": "Enterprises may be classified as micro, small or medium based on investment in plant and machinery or equipment and turnover as prescribed by the Central Government. The classification shall be based on the higher of the two criteria."},
            {"section": "7", "title": "Memorandum of understanding",
             "text": "The Central Government may enter into Memoranda of Understanding with State Governments for implementing programmes for the development of micro, small and medium enterprises."},
            {"section": "8", "title": "Advisory Committee",
             "text": "The Central Government shall constitute an Advisory Committee to advise on matters relating to the classification of enterprises, schemes for promotion, and development of MSMEs."},
            {"section": "9", "title": "Development Commissioner",
             "text": "The Central Government may appoint a Development Commissioner for Micro, Small and Medium Enterprises to coordinate and oversee the implementation of programmes and schemes."},
            {"section": "10", "title": "Office of Development Commissioner",
             "text": "The Development Commissioner shall have the power to: (a) coordinate activities of various agencies for MSME development; (b) monitor implementation of schemes; (c) advise the Government on MSME matters; (d) conduct surveys and studies."},
            {"section": "15", "title": "Delayed payment to micro and small enterprises",
             "text": "Where a buyer receives goods or services from a micro or small enterprise, the buyer shall make payment within the time agreed upon or 45 days from the date of acceptance, whichever is earlier. If payment is delayed, the buyer shall pay interest at three times the bank rate notified by the Reserve Bank."},
            {"section": "16", "title": "Appellate authority for delayed payment",
             "text": "If the buyer fails to make payment within the prescribed time, the micro or small enterprise may approach the Micro and Small Enterprises Facilitation Council for relief. The Council may direct the buyer to pay the amount with interest and costs."},
            {"section": "18", "title": "Micro and Small Enterprises Facilitation Council",
             "text": "The appropriate Government may establish one or more Micro and Small Enterprises Facilitation Councils for conciliation of disputes relating to delayed payments. The Council shall consist of a chairman and members as prescribed."},
            {"section": "22", "title": "Procurement policy",
             "text": "The Central Government shall formulate a policy for procurement of goods and services by Government departments from micro and small enterprises. At least 20% of Government procurement shall be from MSMEs."},
            {"section": "29", "title": "Penalties",
             "text": "Any person who contravenes the provisions of this Act shall be punishable with fine which may extend to Rs 1 lakh for the first contravention and Rs 5 lakh for subsequent contraventions."},
        ]
    },
    {
        "id": "benami-transactions-act",
        "title": "Benami Transactions (Prohibition) Act, 1988",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Benami Transactions (Prohibition) Act, 1988. Extends to whole of India. Amended by the Benami Transactions (Prohibition) Amendment Act, 2016."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) benami transaction means any transaction where property is held by one person and the consideration has been provided by another person; (b) benami property means any property which is the subject matter of a benami transaction; (c) beneficial owner means the person who provides consideration for the property and holds it in the name of another."},
            {"section": "3", "title": "Prohibition of benami transactions",
             "text": "No person shall enter into any benami transaction. A benami transaction includes: (a) property held in the name of a spouse or child for which the consideration is provided by another person; (b) property held in the name of a person in trust or otherwise for the benefit of another."},
            {"section": "4", "title": "Prohibition of right to recover property",
             "text": "No person who is a party to a benami transaction shall be entitled to recover the benami property from the beneficial owner. No suit or other proceeding shall be maintained in any civil court for the recovery of any benami property."},
            {"section": "5", "title": "Properties held benami to be confiscated by Government",
             "text": "Any property which is the subject matter of a benami transaction shall be liable for confiscation by the Central Government. The confiscation shall be without prejudice to any other punishment under this Act."},
            {"section": "6", "title": "Penalty for benami transactions",
             "text": "Any person who enters into a benami transaction shall be punished with rigorous imprisonment which may extend to 7 years, or fine, or both. The fine may extend to 25% of the market value of the benami property."},
            {"section": "7", "title": "Vesting of confiscated property",
             "text": "The confiscation of benami property shall vest in the Central Government free from all encumbrances. The Government may transfer the property to a suitable person or entity, or retain it for public purposes."},
            {"section": "8", "title": "Power of authority",
             "text": "The Central Government shall appoint an Authority (Benami Prohibition Unit) to exercise powers of investigation, attachment and confiscation under this Act. The Authority shall have powers of a civil court."},
            {"section": "9", "title": "Attachment of property",
             "text": "The Authority may attach any property which is suspected to be a benami property for a period not exceeding 30 days, pending investigation. The attachment may be extended with the approval of the Adjudicating Authority."},
            {"section": "10", "title": "Adjudicating Authority",
             "text": "The Central Government shall constitute an Adjudicating Authority for adjudication in relation to attachment and confiscation of benami property. The Authority shall consist of a Chairperson and members."},
            {"section": "18", "title": "Appellate Tribunal",
             "text": "The Central Government shall establish an Appellate Tribunal for hearing appeals against orders of the Adjudicating Authority. The Tribunal shall consist of a Chairperson and members."},
            {"section": "53", "title": "Offence by companies",
             "text": "Where an offence under this Act has been committed by a company, every person who was in charge of and responsible for the company's conduct shall be deemed guilty. The company shall also be punished with fine up to 25% of the market value of the benami property."},
        ]
    },
    {
        "id": "black-money-act",
        "title": "Black Money (Undisclosed Foreign Income and Assets) and Imposition of Tax Act, 2015",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Black Money (Undisclosed Foreign Income and Assets) and Imposition of Tax Act, 2015. Extends to whole of India. Came into force on 1st April 2016."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) undisclosed foreign income means any income from a source located outside India which has not been disclosed in any return of income; (b) undisclosed asset means any asset located outside India which has not been disclosed in any return of income; (c) foreign income means income arising from any source outside India."},
            {"section": "3", "title": "Tax on undisclosed foreign income and assets",
             "text": "Every person who is a resident of India shall be liable to pay tax on his total undisclosed foreign income and assets at the rate of 30% per annum, plus a penalty of 90% of the tax, making the effective rate 120%."},
            {"section": "4", "title": "Tax on undisclosed foreign assets",
             "text": "Any undisclosed asset located outside India shall be taxed at 30% per annum for each year the asset has been held, from the year of acquisition. A penalty of 90% of the tax shall also be imposed."},
            {"section": "5", "title": "Penalty for non-disclosure",
             "text": "In addition to tax and penalty, a further penalty of Rs 10 lakh may be imposed for failure to disclose foreign income or assets in the return of income."},
            {"section": "7", "title": "Prosecution for concealment",
             "text": "Any person who has undisclosed foreign income or assets and fails to disclose the same shall be punishable with rigorous imprisonment which shall not be less than 3 years but which may extend to 10 years, and shall also be liable to fine."},
            {"section": "8", "title": "Penalty for failure to furnish information",
             "text": "Any person who fails to furnish information in respect of foreign income or assets as required under this Act shall be punishable with imprisonment up to 6 months, or fine up to Rs 5 lakh, or both."},
            {"section": "10", "title": "Power to search and seize",
             "text": "The income tax authorities may search any place and seize documents, books of account, records or any other material relevant to the investigation of undisclosed foreign income or assets."},
            {"section": "11", "title": "Assessment and recovery",
             "text": "The income tax authorities may make assessments or reassessments of undisclosed foreign income and assets, and recover tax and penalty in the manner prescribed under the Income Tax Act, 1961."},
            {"section": "13", "title": "Offence to be cognizable and non-bailable",
             "text": "Any offence under this Act shall be cognizable and non-bailable. The provisions of the Code of Criminal Procedure shall apply to the arrest, bail and trial of offences under this Act."},
            {"section": "15", "title": "No compounding of offences",
             "text": "No offence under this Act shall be compounded. No prosecution shall be instituted against any person except with the previous sanction of the Principal Chief Commissioner of Income Tax."},
        ]
    },
]

if __name__ == "__main__":
    print("Creating commercial & financial acts...")
    for act in ACTS:
        create_act(act["id"], act["title"], act["sections"])
    print(f"Done: {len(ACTS)} acts created.")
