#!/usr/bin/env python3
"""Create missing environment & labour acts for S3 KB."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from s3_upload import create_act

ACTS = [
    {
        "id": "wildlife-protection-act",
        "title": "Wildlife (Protection) Act, 1972",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Wildlife (Protection) Act, 1972. Extends to whole of India except Jammu & Kashmir (now extended there too). Came into force on 9th September 1972."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) animal includes any fish, amphibian, mammal, reptile, bird or any other creature; (b) wildlife includes any animal, plant and aquatic organism; (c) sanctuary means an area declared under section 18; (d) national park means an area declared under section 35; (e) hunting includes killing, poisoning, snaring, capturing, injuring or destroying any wild animal."},
            {"section": "4", "title": "Prohibition of hunting",
             "text": "No person shall hunt any wild animal specified in Schedule I, II, III, IV or V except with the permission of the Chief Wildlife Warden. Hunting in a sanctuary or national park is strictly prohibited."},
            {"section": "9", "title": "Prohibition on hunting certain wild animals",
             "text": "No person shall hunt any wild animal specified in Schedule I (such as tigers, lions, elephants, rhinoceros) except with the previous permission of the Central Government."},
            {"section": "10", "title": "Protection of wild animals",
             "text": "Any person who hunts any wild animal in contravention of this Act shall be punished with imprisonment not less than 3 years but which may extend to 7 years, and fine not less than Rs 10,000."},
            {"section": "16", "title": "National Parks",
             "text": "The State Government may declare any area as a national park if it considers that such area is ecologically, geomorphologically, or naturally valuable. No person shall enter a national park without permission."},
            {"section": "18", "title": "Wildlife sanctuaries",
             "text": "The State Government may declare any area as a wildlife sanctuary if it considers that such area is important for the protection of wildlife. No person shall enter a sanctuary without permission of the Chief Wildlife Warden."},
            {"section": "27", "title": "Hunting in sanctuaries and national parks",
             "text": "Whoever hunts any wild animal in a sanctuary or national park shall be punished with imprisonment not less than 3 years but which may extend to 7 years, and fine not less than Rs 10,000."},
            {"section": "31", "title": "Destruction of wild animals causing damage",
             "text": "The Chief Wildlife Warden may order the destruction of any wild animal which is dangerous to human life or property, subject to conditions. The order shall specify the method of destruction."},
            {"section": "33", "title": "Management plan for sanctuaries",
             "text": "The State Government shall prepare a management plan for every sanctuary and national park, which shall include measures for conservation, management of habitats, and regulation of tourism."},
            {"section": "38", "title": "Power to declare protected areas",
             "text": "The Central Government may declare any area as a protected area for the purposes of this Act. Protected areas include national parks, wildlife sanctuaries, tiger reserves, and conservation reserves."},
            {"section": "39", "title": "Prohibition on trade in wildlife",
             "text": "No person shall trade in any wild animal or any part or product thereof. Any person who trades in wildlife shall be punished with imprisonment not less than 3 years which may extend to 7 years, and fine not less than Rs 10,000."},
            {"section": "50", "title": "Offences by companies",
             "text": "Where an offence under this Act has been committed by a company, every person who was in charge of and responsible for the company's conduct shall be deemed guilty. The company shall also be punished with fine."},
        ]
    },
    {
        "id": "forest-conservation-act",
        "title": "Forest (Conservation) Act, 1980",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Forest (Conservation) Act, 1980. Extends to whole of India except Jammu & Kashmir (now extended). Came into force on 25th October 1980."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) forest land means any land which is a forest within the meaning of the Indian Forest Act, 1927, or which may be declared as a forest by the State Government; (b) State Government includes the administrator of a Union Territory; (c) national park means a national park declared under the Wildlife Protection Act, 1972."},
            {"section": "2A", "title": "Restriction on dereservation of forests",
             "text": "No State Government shall dereserve any forest which has been reserved under the Indian Forest Act, 1927, without the prior approval of the Central Government."},
            {"section": "2B", "title": "Restriction on diversion of forest land",
             "text": "No State Government shall make any order permitting the diversion of forest land for any non-forest purpose without the prior approval of the Central Government. Non-forest purpose includes any activity other than afforestation."},
            {"section": "3", "title": "Prior approval of Central Government",
             "text": "The prior approval of the Central Government is required for: (a) diversion of forest land for non-forest purposes; (b) construction of roads, railways, canals or other works in forest land; (c) mining or quarrying in forest land; (d) any other activity which may affect the forest."},
            {"section": "3A", "title": "Compensatory afforestation",
             "text": "Where forest land is diverted for non-forest purposes, the person responsible shall undertake compensatory afforestation on an equal area of non-forest land, or on twice the area of degraded forest land, as may be specified by the Central Government."},
            {"section": "4", "title": "Penalty for contravention",
             "text": "Any person who contravenes any provision of this Act shall be punished with imprisonment up to 15 days, or fine up to Rs 500, or both. In case of continuing contravention, additional fine up to Rs 50 per day."},
            {"section": "4A", "title": "Appraisal of proposals",
             "text": "The Central Government shall constitute an Expert Appraisal Committee to appraise all proposals involving diversion of forest land. The Committee shall consider the impact on forest and wildlife before recommending approval."},
            {"section": "4B", "title": "National Board for Wildlife",
             "text": "The National Board for Wildlife shall be constituted to review all matters relating to wildlife conservation and to approve proposals for diversion of forest land in and around national parks and sanctuaries."},
            {"section": "5", "title": "Power to make rules",
             "text": "The Central Government may make rules to carry out the purposes of this Act. Such rules may provide for the procedure for obtaining approval, the conditions for diversion, and the manner of compensatory afforestation."},
        ]
    },
    {
        "id": "water-act",
        "title": "Water (Prevention and Control of Pollution) Act, 1974",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Water (Prevention and Control of Pollution) Act, 1974. Extends to whole of India. Came into force on 23rd March 1974."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) Board means the State Board constituted under section 4; (b) Central Board means the Central Pollution Control Board constituted under section 3; (c) pollutant includes any solid, liquid or gaseous substance which may contaminate water; (d) pollution means contamination of water by any substance."},
            {"section": "3", "title": "Central Pollution Control Board",
             "text": "The Central Government shall constitute the Central Pollution Control Board to exercise the powers and perform the functions conferred on it under this Act. The Board shall consist of a Chairman and members nominated by the Central Government."},
            {"section": "4", "title": "State Pollution Control Board",
             "text": "The State Government shall constitute the State Pollution Control Board to exercise the powers and perform the functions conferred on it under this Act. The Board shall consist of a Chairman and members nominated by the State Government."},
            {"section": "16", "title": "Functions of Central Board",
             "text": "The Central Board shall: (a) advise the Central Government on matters relating to prevention and control of water pollution; (b) coordinate the activities of State Boards; (c) provide technical assistance to State Boards; (d) conduct research and development; (e) collect and disseminate information relating to water pollution."},
            {"section": "17", "title": "Functions of State Board",
             "text": "The State Board shall: (a) inspect sewage and trade effluents; (b) collect and analyse data relating to water pollution; (c) advise the State Government on matters relating to water pollution; (d) issue directions to industries for prevention and control of water pollution."},
            {"section": "20", "title": "Power of State Board to make standards",
             "text": "The State Board may, with the approval of the State Government, make standards for the quality of sewage and trade effluents to be discharged into water bodies."},
            {"section": "21", "title": "Prohibition on discharge of pollutants",
             "text": "No person shall knowingly cause or permit any pollutant to enter any stream or well or any other water body. Any person who contravenes this provision shall be punished with imprisonment up to 3 years, or fine up to Rs 10,000 per day of contravention, or both."},
            {"section": "24", "title": "Restriction on use of stream for certain purposes",
             "text": "No person shall use any stream or well for disposal of pollutants except with the consent of the State Board. The consent shall be obtained before establishing any industry or operation."},
            {"section": "25", "title": "Consent of State Board required",
             "text": "No person shall establish or operate any industry, operation or process without the consent of the State Board. The State Board shall grant consent within 4 months of application, or the consent shall be deemed to have been granted."},
            {"section": "33", "title": "Powers of State Board to give directions",
             "text": "The State Board may give directions to any person, industry or local authority for: (a) stopping or regulating discharge of pollutants; (b) installing pollution control equipment; (c) complying with prescribed standards."},
            {"section": "33A", "title": "Power to take samples",
             "text": "Any officer authorised by the State Board may take samples of water from any stream or well for analysis. The analysis shall be conducted in accordance with prescribed methods."},
            {"section": "40", "title": "Penalty for contravention",
             "text": "Any person who contravenes any provision of this Act shall be punished with imprisonment up to 3 years, or fine up to Rs 10,000 per day of contravention, or both. For continuing contravention, additional fine up to Rs 5,000 per day."},
        ]
    },
    {
        "id": "air-act",
        "title": "Air (Prevention and Control of Pollution) Act, 1981",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Air (Prevention and Control of Pollution) Act, 1981. Extends to whole of India. Came into force on 16th May 1981."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) air pollutant means any solid, liquid or gaseous substance including noise; (b) air pollution means the presence of any air pollutant in the atmosphere; (c) Board means the State Board constituted under section 4; (d) emission means any release of air pollutants from any source."},
            {"section": "3", "title": "Central Pollution Control Board",
             "text": "The Central Pollution Control Board constituted under the Water Act, 1974, shall also exercise the powers and perform the functions conferred on the Central Board under this Act."},
            {"section": "4", "title": "State Pollution Control Board",
             "text": "The State Pollution Control Board constituted under the Water Act, 1974, shall also exercise the powers and perform the functions conferred on the State Board under this Act."},
            {"section": "16", "title": "Functions of Central Board",
             "text": "The Central Board shall: (a) advise the Central Government on matters relating to air pollution; (b) coordinate the activities of State Boards; (c) provide technical assistance to State Boards; (d) conduct research and development; (e) collect and disseminate information relating to air pollution."},
            {"section": "17", "title": "Functions of State Board",
             "text": "The State Board shall: (a) inspect air pollution control areas; (b) collect and analyse data relating to air pollution; (c) advise the State Government on matters relating to air pollution; (d) issue directions to industries for prevention and control of air pollution."},
            {"section": "20", "title": "Consent of State Board required",
             "text": "No person shall establish or operate any industrial plant in an air pollution control area without the consent of the State Board. The State Board shall grant consent within 4 months of application."},
            {"section": "21", "title": "Emission standards",
             "text": "The State Board may, with the approval of the State Government, prescribe emission standards for any industry, operation or process. The standards shall be consistent with the national standards."},
            {"section": "22", "title": "Restriction on use of fuels",
             "text": "The State Government may, in consultation with the State Board, restrict the use of any fuel which causes air pollution in any air pollution control area. The restriction may include prohibition of certain fuels."},
            {"section": "31", "title": "Prohibition on emission of pollutants in excess of standards",
             "text": "No person shall cause or allow emission of any air pollutant in excess of the prescribed standards. Any person who contravenes this provision shall be punished with imprisonment up to 5 years, or fine up to Rs 10,000 per day of contravention, or both."},
            {"section": "33", "title": "Powers of State Board to give directions",
             "text": "The State Board may give directions to any person, industry or local authority for: (a) stopping or regulating emission of pollutants; (b) installing pollution control equipment; (c) complying with prescribed emission standards."},
            {"section": "37", "title": "Penalty for contravention",
             "text": "Any person who contravenes any provision of this Act shall be punished with imprisonment up to 5 years, or fine up to Rs 10,000 per day of contravention, or both. For continuing contravention, additional fine up to Rs 5,000 per day."},
            {"section": "39", "title": "Offences by companies",
             "text": "Where an offence under this Act has been committed by a company, every person who was in charge of and responsible for the company's conduct shall be deemed guilty. The company shall also be punished with fine."},
        ]
    },
    {
        "id": "national-green-tribunal-act",
        "title": "National Green Tribunal Act, 2010",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the National Green Tribunal Act, 2010. Extends to whole of India. Came into force on 18th October 2010."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) Tribunal means the National Green Tribunal established under section 3; (b) environmental dispute means a dispute which involves enforcement of any environmental right or question relating to environmental protection; (c) environmental law means any law for the time being in force relating to environment; (d) environmental question means any question relating to the environment."},
            {"section": "3", "title": "Establishment of Tribunal",
             "text": "The Central Government shall, by notification, establish the National Green Tribunal for effective and expeditious disposal of cases relating to environmental protection and conservation of forests and other natural resources. The Tribunal shall have the jurisdiction to hear all civil cases relating to environmental issues."},
            {"section": "4", "title": "Composition of Tribunal",
             "text": "The Tribunal shall consist of a Chairperson and such number of Judicial and Expert members as the Central Government may think fit. The Chairperson shall be a former Chief Justice of a High Court or a former Judge of the Supreme Court. Judicial members shall be former Judges of High Courts. Expert members shall have experience in environmental science or related fields."},
            {"section": "5", "title": "Qualifications of members",
             "text": "The Chairperson shall have been a Chief Justice of a High Court or a Judge of the Supreme Court. Judicial members shall have been Judges of High Courts for at least 5 years. Expert members shall have at least 15 years of experience in environmental science, ecology, or related fields."},
            {"section": "9", "title": "Jurisdiction of Tribunal",
             "text": "The Tribunal shall have jurisdiction over all civil cases involving substantial questions relating to environment. The Tribunal may hear: (a) disputes relating to environmental rights; (b) applications for environmental clearances; (c) matters relating to pollution control; (d) matters relating to conservation of forests and natural resources."},
            {"section": "10", "title": "Original jurisdiction",
             "text": "Any person aggrieved by an order or decision of the Central Government, State Government, or any other authority relating to environmental issues may file an application before the Tribunal within 6 months of the order or decision."},
            {"section": "14", "title": "Powers of Tribunal",
             "text": "The Tribunal shall have the powers of a civil court. The Tribunal may: (a) issue orders including interim orders; (b) direct any person to comply with its orders; (c) impose penalties for non-compliance; (d) award compensation for environmental damage."},
            {"section": "15", "title": "Relief and compensation",
             "text": "The Tribunal may award compensation for any loss or damage caused to any person or the environment due to contravention of environmental laws. The compensation may include: (a) cost of restoration; (b) damages for loss of biodiversity; (c) compensation for affected persons; (d) cost of remediation."},
            {"section": "20", "title": "Bar of jurisdiction of civil courts",
             "text": "No civil court shall have jurisdiction to entertain any suit or application in respect of any matter which the Tribunal is empowered to adjudicate under this Act."},
            {"section": "25", "title": "Appeal to Supreme Court",
             "text": "Any person aggrieved by an order of the Tribunal may file an appeal before the Supreme Court within 90 days of the order. The Supreme Court may confirm, modify or set aside the order."},
            {"section": "26", "title": "Penalty for non-compliance",
             "text": "Any person who fails to comply with any order of the Tribunal shall be punished with imprisonment up to 3 years, or fine up to Rs 10 crore, or both. In case of continuing non-compliance, additional fine up to Rs 1 lakh per day."},
        ]
    },
    {
        "id": "biological-diversity-act",
        "title": "Biological Diversity Act, 2002",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Biological Diversity Act, 2002. Extends to whole of India. Came into force on different dates in different States."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) biological diversity means the variability among living organisms from all sources including terrestrial, marine and aquatic ecosystems; (b) biological resource means plants, animals and micro-organisms or parts thereof; (c) biological material includes genetic material; (d) biodiversity heritage site means any site declared as such under section 37."},
            {"section": "3", "title": "Regulation of access to biological resources",
             "text": "No person shall obtain any biological resource for commercial utilization or bio-survey and bio-utilization from India without the approval of the National Biodiversity Authority or State Biodiversity Board. Foreign nationals must obtain prior approval."},
            {"section": "6", "title": "Functions of National Biodiversity Authority",
             "text": "The National Biodiversity Authority shall: (a) regulate and grant approval for access to biological resources; (b) advise the Central Government on matters relating to biological diversity; (c) promote conservation and sustainable use of biological diversity; (d) establish registers of biological resources."},
            {"section": "8", "title": "Functions of State Biodiversity Board",
             "text": "The State Biodiversity Board shall: (a) advise the State Government on matters relating to biological diversity; (b) regulate access to biological resources within the State; (c) promote conservation and sustainable use of biological diversity; (d) establish biodiversity heritage sites."},
            {"section": "17", "title": "Benefit sharing",
             "text": "Where biological resources are accessed for commercial utilization, the benefit arising from such access shall be shared with the local communities and the National Biodiversity Authority. The sharing shall be in the manner prescribed."},
            {"section": "21", "title": "Biodiversity Heritage Sites",
             "text": "The State Government may declare any area as a biodiversity heritage site if it considers that such area is important for biological diversity. The State Biodiversity Board shall develop a management plan for the site."},
            {"section": "23", "title": "Penalty for contravention",
             "text": "Any person who accesses biological resources without approval shall be punished with imprisonment up to 5 years, or fine up to Rs 10 lakh, or both. For continuing contravention, additional fine up to Rs 1 lakh per day."},
            {"section": "25", "title": "Offences by companies",
             "text": "Where an offence under this Act has been committed by a company, every person who was in charge of and responsible for the company's conduct shall be deemed guilty. The company shall also be punished with fine."},
        ]
    },
    {
        "id": "factories-act",
        "title": "Factories Act, 1948",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Factories Act, 1948. Extends to whole of India. Came into force on 1st April 1949."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) factory means any premises where manufacturing process is carried on with the aid of power, or without power with more than 10 workers; (b) manufacturing process means any process for making, altering, repairing, finishing, packing, oiling, cleaning, testing or adapting any article or substance; (c) worker means any person employed in a factory with or without remuneration; (d) occupier means the person who has ultimate control over the affairs of the factory."},
            {"section": "4", "title": "Approval and licensing of factories",
             "text": "No person shall carry on or cause to be carried on any manufacturing process in a factory unless he has obtained permission from the Chief Inspector. The application shall be accompanied by prescribed particulars and fees."},
            {"section": "6A", "title": "Registration of workers",
             "text": "Every occupier shall maintain a register of all workers employed in the factory. The register shall contain the name, date of birth, nature of work, and other prescribed particulars. The register shall be open for inspection by the Chief Inspector."},
            {"section": "7", "title": "Cleanliness and drainage",
             "text": "Every factory shall be kept clean and free from effluvia arising from any drain or nuisance. The floors, walls, and ceilings shall be cleaned at least once a week. Adequate drainage shall be provided."},
            {"section": "8", "title": "Ventilation and temperature",
             "text": "Every factory shall maintain sufficient ventilation and reasonable temperature for the comfort of workers. The effective temperature shall not exceed 30 degrees Celsius. Exhaust fans, ventilators or other means shall be provided."},
            {"section": "9", "title": "Dust and fume control",
             "text": "Effective measures shall be taken in every factory to prevent accumulation of dust, fume or other impurities. Exhaust systems shall be provided where dust or fume is generated."},
            {"section": "11", "title": "Lighting",
             "text": "Every factory shall be sufficiently lit by natural or artificial light. The lighting shall be adequate for the work being carried on. Inadequate lighting is a violation of this Act."},
            {"section": "13", "title": "Drinking water",
             "text": "Every factory shall provide and maintain an adequate supply of drinking water. The water shall be pure and wholesome. The drinking water points shall be marked and maintained in a sanitary condition."},
            {"section": "14", "title": "Latrines and urinals",
             "text": "Every factory shall provide and maintain sufficient and suitable latrines and urinals for the use of workers. The latrines and urinals shall be kept in a clean and sanitary condition."},
            {"section": "16", "title": "Accommodation for eating",
             "text": "Where food is not provided in the factory, adequate arrangements shall be made for workers to eat their food. The eating area shall be kept clean and free from dust and fumes."},
            {"section": "21", "title": "Fencing of machinery",
             "text": "Every dangerous part of any machinery shall be securely fenced. The fencing shall be in position before the machinery is set in motion. No person shall remove or interfere with any fencing."},
            {"section": "22", "title": "Work on or near machinery in motion",
             "text": "No person shall clean, lubricate or adjust any machinery while it is in motion. The operator shall wear tight-fitting clothing. No person shall operate machinery without proper training."},
            {"section": "36", "title": "Precautions against dangerous fumes",
             "text": "No person shall enter any confined space where dangerous fumes are likely to be present without adequate ventilation. A responsible person shall be stationed outside to render assistance."},
            {"section": "40A", "title": "Maximum permissible limits of exposure",
             "text": "The Central Government may prescribe the maximum permissible limits of exposure to chemical and toxic substances. The occupier shall ensure that no worker is exposed to levels exceeding the prescribed limits."},
            {"section": "41", "title": "Annual health examination",
             "text": "Every worker employed in a factory shall be given an annual health examination. The results shall be recorded in the health register. The occupier shall bear the cost of the examination."},
            {"section": "44", "title": "Working hours",
             "text": "No worker shall be required to work more than 48 hours in a week. No worker shall work more than 9 hours in a day. The worker shall be entitled to at least one day of rest in every 7 days."},
            {"section": "51", "title": "Spreadover",
             "text": "The period of work in any factory shall be so arranged that the spreadover, inclusive of intervals of rest, shall not exceed 10 hours 30 minutes in any day."},
            {"section": "52", "title": "Intervals for rest",
             "text": "No worker shall work for more than 5 hours without an interval of at least 30 minutes for rest. The interval shall be granted as near the middle of the shift as possible."},
            {"section": "54", "title": "Night shifts",
             "text": "Where a worker works on a shift which extends beyond 10 pm, and such shift does not consist of two consecutive shifts of 8 hours each, the worker shall be entitled to at least one hour of rest. The night shift shall not be less than 7 hours."},
            {"section": "56", "title": "Overtime",
             "text": "Where a worker works more than 48 hours in a week or more than 9 hours in a day, he shall be entitled to overtime wages at twice the ordinary rate of wages for every hour of work in excess."},
            {"section": "58", "title": "Record of overtime",
             "text": "The occupier shall maintain a register of overtime work done by workers. The register shall contain the name of the worker, hours of overtime work, and the overtime wages paid."},
            {"section": "61", "title": "Annual leave with wages",
             "text": "Every worker shall be entitled to annual leave with wages for at least 15 days for every 240 days of work. The leave shall be in addition to holidays and casual leave."},
            {"section": "63", "title": "Notice of period of work",
             "text": "A notice showing the period of work for every worker shall be displayed in the factory. The notice shall show the shift timings, intervals, and holidays."},
            {"section": "77", "title": "Compensation for injury",
             "text": "Where a worker is injured in the course of employment, the occupier shall pay compensation as prescribed under the Workmen's Compensation Act, 1923. The compensation shall be paid without delay."},
            {"section": "88", "title": "Notice of accident",
             "text": "Where an accident occurs in a factory causing death or serious bodily injury, the occupier shall give notice to the prescribed authority within 12 hours. The notice shall contain prescribed particulars."},
            {"section": "92", "title": "Penalties",
             "text": "Any person who contravenes any provision of this Act shall be punished with imprisonment up to 2 years, or fine up to Rs 1 lakh, or both. For continuing contravention, additional fine up to Rs 1,000 per day."},
        ]
    },
    {
        "id": "essential-commodities-act",
        "title": "Essential Commodities Act, 1955",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Essential Commodities Act, 1955. Extends to whole of India. Came into force on 1st April 1955."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) essential commodity means any commodity specified in the Schedule, including foodstuffs, petroleum, raw cotton, drugs, fertilizers; (b) dealer means any person who carries on the business of buying or selling essential commodities; (c) distribution means making available essential commodities to consumers; (d) producer means any person engaged in production of essential commodities."},
            {"section": "3", "title": "Power to control production, supply and distribution",
             "text": "If the Central Government is of opinion that it is necessary or expedient in the public interest to control the production, supply or distribution of any essential commodity, it may by order provide for: (a) regulating production, supply or distribution; (b) fixing prices; (c) regulating storage, transport and sale; (d) requiring dealers to maintain records."},
            {"section": "4", "title": "Orders under section 3",
             "text": "An order under section 3 may: (a) require a dealer to sell the commodity to the Government or to persons specified by the Government; (b) regulate or prohibit the sale or distribution of the commodity; (c) control the price at which the commodity may be sold; (d) require production, storage or transport of the commodity."},
            {"section": "5", "title": "Penalty for contravention of orders",
             "text": "Any person who contravenes any order under section 3 shall be punished with imprisonment up to 7 years, or fine, or both. The fine may extend to Rs 1 lakh for the first offence and Rs 5 lakh for subsequent offences."},
            {"section": "6", "title": "Power of search and seizure",
             "text": "Any officer authorised by the Central Government may search any premises, seize essential commodities and records, and detain any person suspected of contravening an order under this Act."},
            {"section": "6A", "title": "Confiscation of commodities",
             "text": "Where any essential commodity is seized in contravention of an order under section 3, the commodity may be confiscated to the Central Government. The confiscation may be ordered by the court after due inquiry."},
            {"section": "7", "title": "Cognizance of offences",
             "text": "No court shall take cognizance of an offence under this Act except upon a complaint made by an officer authorised by the Central Government. The complaint shall be filed within 6 months of the offence."},
            {"section": "8", "title": "Offences by companies",
             "text": "Where an offence under this Act has been committed by a company, every person who was in charge of and responsible for the company's conduct shall be deemed guilty. The company shall also be punished with fine."},
            {"section": "9", "title": "Power to give directions",
             "text": "The Central Government may give directions to State Governments regarding the implementation of this Act. The directions may include the manner of distribution, pricing, and storage of essential commodities."},
            {"section": "10", "title": "Protection of action taken in good faith",
             "text": "No suit, prosecution or legal proceeding shall lie against the Government or any officer for anything done in good faith under this Act."},
        ]
    },
]

if __name__ == "__main__":
    print("Creating environment & labour acts...")
    for act in ACTS:
        create_act(act["id"], act["title"], act["sections"])
    print(f"Done: {len(ACTS)} acts created.")
