#!/usr/bin/env python3
"""Upload Practical Legal Guides 4 to S3."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from s3_upload import create_act

create_act("practical-guides-4", "Practical Legal Guides - Part 4", [
    {"section": "1", "title": "How to Check Case Status Online",
     "text": "Step-by-step guide to check your case status online:\n\n1. eCourts Portal (https://ecourts.gov.in/): Visit the eCourts website, click on Case Status, enter your case number, party name, or FIR number, select your state and district, and click Search.\n\n2. High Court websites: Each High Court has its own website. Visit the relevant High Court website, click on Case Status or Cause List, and enter your case details.\n\n3. Supreme Court (https://main.sci.gov.in/): Visit the Supreme Court website, click on Case Status, and enter your case number or party name.\n\n4. National Judicial Data Grid (NJDG): Visit https://njdg.ecourts.gov.in/ and search by case number, party name, or FIR number. Provides real-time data on pending cases.\n\n5. What information you can find: Next date of hearing, current status (pending, disposed, etc.), orders and judgments, case history, cause list.\n\n6. Tips: Keep your case number handy, note down the court and judge name, check regularly for updates, download and save important orders."},

    {"section": "2", "title": "How to Get a Police Clearance Certificate",
     "text": "Step-by-step guide to obtain a Police Clearance Certificate (PCC):\n\n1. Eligibility: Indian citizens applying for employment abroad, Indian citizens emigrating, foreign nationals residing in India.\n\n2. Documents required: Valid passport (original and photocopy), Aadhaar card (original and photocopy), address proof (utility bill, rental agreement), passport-size photographs (2 copies), application form, fee payment receipt.\n\n3. Procedure: Visit your local police station, submit the application with all documents, police verification will be conducted, PCC will be issued within 2-4 weeks.\n\n4. Online application: Visit https://passportindia.gov.in/, click on Police Clearance Certificate, fill in the application form, upload required documents, pay the fee online.\n\n5. Fee: Rs. 500 for Indian citizens, Rs. 1000 for foreign nationals.\n\n6. Timeline: Normal processing 2-4 weeks, urgent processing 1-2 weeks, validity 6 months from date of issue.\n\n7. Important notes: PCC is required for immigration purposes, employment abroad, and long-term visa applications. Keep multiple copies."},

    {"section": "3", "title": "How to Respond to a Legal Notice",
     "text": "Step-by-step guide to respond to a legal notice:\n\n1. Understand the legal notice: Read carefully, note claims made against you, identify legal provisions cited, note the deadline for response.\n\n2. Gather documents: Collect all relevant documents, gather evidence supporting your position, get copies of agreements or contracts.\n\n3. Consult a lawyer: Engage a qualified lawyer, share all documents, discuss your legal position, get advice on the best course of action.\n\n4. Draft the response: The response should be drafted by your lawyer, address each point in the notice, provide your version of events, include supporting evidence.\n\n5. Send the response: Send by registered post, keep proof of delivery, send a copy to the opposing partys lawyer, retain copies of all correspondence.\n\n6. Important points: Do not ignore the legal notice, respond within the stipulated time, do not admit liability without legal advice, keep all communications professional.\n\n7. If you disagree: State objections clearly, provide counter-evidence, state legal provisions supporting your position, reserve your rights to take legal action.\n\n8. If you agree: Accept the claims made, propose a settlement if possible, negotiate the terms, document the settlement."},

    {"section": "4", "title": "How to Follow Up on an RTI Application",
     "text": "Step-by-step guide to follow up on an RTI application:\n\n1. If no response within 30 days: File a first appeal with the concerned Public Information Officer (PIO). The first appeal must be filed within 30 days of the expiry of the 30-day period. The first appellate authority must decide within 45 days.\n\n2. If no response to first appeal: File a second appeal with the Central Information Commission or State Information Commission. The second appeal must be filed within 90 days of the first appeal decision. The Information Commission must decide within 30 days.\n\n3. Penalty for non-compliance: The PIO may be liable to pay a penalty of Rs. 250 per day. The maximum penalty is Rs. 25,000. The PIO may also be liable for disciplinary action.\n\n4. Tips for follow-up: Keep copies of all RTI applications and responses, file appeals within the stipulated time, provide complete details of the original application.\n\n5. Common reasons for delay: Large volume of information requested, information requires consultation with other departments, information is sensitive in nature.\n\n6. If information is denied: Check if the exemption under Section 8 applies, file a first appeal if you disagree, file a second appeal if the first appeal is rejected."},

    {"section": "5", "title": "Police Complaint vs FIR - Key Differences",
     "text": "Understanding the difference between a police complaint and an FIR:\n\n1. Police Complaint: A written or oral statement to the police, can be about any matter, not necessarily a cognizable offence. Police may or may not register an FIR. Used for minor offences or non-cognizable offences.\n\n2. FIR (First Information Report): A written record of a cognizable offence, must be registered by the police if a cognizable offence is disclosed, triggers a mandatory police investigation, must be filed at the police station having jurisdiction.\n\n3. When to file a police complaint: For non-cognizable offences, minor offences, matters requiring police assistance, general complaints about nuisance or harassment.\n\n4. When to file an FIR: For cognizable offences (theft, robbery, assault, murder, etc.), serious offences, offences under the Indian Penal Code, when immediate police investigation is required.\n\n5. Key differences: Complaint may not trigger investigation; FIR triggers mandatory investigation. Complaint can be oral or written; FIR must be written. Complaint may be filed at any police station; FIR must be filed at the correct jurisdiction.\n\n6. What to include in a complaint: Your name and address, date and time of the incident, place of the incident, details of the incident, names of witnesses.\n\n7. What to include in an FIR: Your name and address, date and time of the offence, place of the offence, details of the offence, names of the accused, names of witnesses."},

    {"section": "6", "title": "How to File a Consumer Complaint Online",
     "text": "Step-by-step guide to file a consumer complaint online:\n\n1. Online complaint portal: Visit https://consumerhelpline.gov.in/, register on the National Consumer Helpline, file a complaint online, track the status of your complaint.\n\n2. Online dispute resolution: Visit https://edaakhil.nic.in/, register on the E-Daakhil portal, file a consumer complaint online, participate in virtual hearings.\n\n3. Documents required: Bill or invoice, warranty card (if applicable), correspondence with the seller, photographs of the defective product, medical bills (if applicable).\n\n4. Forum to approach: District Consumer Disputes Redressal Commission (claims up to Rs. 1 crore), State Consumer Disputes Redressal Commission (Rs. 1 crore to Rs. 10 crore), National Consumer Disputes Redressal Commission (above Rs. 10 crore).\n\n5. Fee: No fee for complaints up to Rs. 5 lakh, Rs. 200 for Rs. 5 lakh to Rs. 10 lakh, Rs. 400 for Rs. 10 lakh to Rs. 1 crore.\n\n6. Timeline: Complaint must be filed within 2 years of the cause of action, commission must dispose of complaint within 3-5 months."},

    {"section": "7", "title": "How to Get a Duplicate Document",
     "text": "Step-by-step guide to obtain duplicate documents:\n\n1. Types of documents: Property documents (sale deed, gift deed, will), educational certificates, identity documents (Aadhaar, PAN, passport), financial documents, insurance policies.\n\n2. Property documents: File a police complaint, publish a notice in two newspapers (one English, one vernacular), wait 15 days for objections, apply to the sub-registrar for a certified copy.\n\n3. Educational certificates: File a police complaint, apply to the educational institution, provide proof of identity and enrollment, pay the prescribed fee.\n\n4. Identity documents: Aadhaar - visit nearest Aadhaar centre; PAN - apply online at NSDL; Passport - apply online at passportindia.gov.in.\n\n5. Financial documents: File a police complaint, notify the company or bank in writing, apply for a duplicate document, pay the prescribed fee.\n\n6. Important points: Always keep copies of important documents, store documents in a safe place, consider digitizing important documents, file a police complaint immediately if a document is lost.\n\n7. Timeline: Police complaint is immediate, newspaper notice takes 15 days, duplicate document takes 1-4 weeks."},

    {"section": "8", "title": "How to Apply for Bail",
     "text": "Step-by-step guide to apply for bail:\n\n1. Types of bail: Regular bail (for offences punishable with less than 7 years), anticipatory bail (for offences punishable with 7 years or more), interim bail (temporary bail pending hearing), default bail (for failure to complete investigation within 60/90 days).\n\n2. Documents required: Bail application, FIR copy, charge sheet (if filed), identity proof of the accused, address proof of the surety, medical certificates (if applicable).\n\n3. Procedure: Engage a lawyer, draft the bail application, file before the appropriate court, attend the hearing, argue the bail application.\n\n4. Grounds for bail: Not likely to abscond, not likely to tamper with evidence, not likely to influence witnesses, has roots in the community, has a fixed address and stable job.\n\n5. Conditions for bail: Shall not leave the country, shall not contact witnesses, shall not commit any offence, shall attend all court hearings, shall furnish a bail bond.\n\n6. Bail bond: Must be for a sum fixed by the court, executed by the accused and the surety. The surety must be a person of means and good character, resident within the jurisdiction of the court.\n\n7. Timeline: Regular bail hearing within 1-7 days, anticipatory bail hearing within 1-7 days, interim bail hearing within 1-3 days."},

    {"section": "9", "title": "How to Contest an Election",
     "text": "Step-by-step guide to contest an election in India:\n\n1. Eligibility: Citizen of India, minimum age 25 years for Lok Sabha/Assembly and 30 years for Rajya Sabha, registered voter in any constituency, not disqualified under any law.\n\n2. Documents required: Nomination form, affidavit (Form 26), electoral roll extract, caste certificate (if applicable), age proof, address proof, security deposit receipt.\n\n3. Procedure: File nomination papers with the Returning Officer, pay the security deposit (Rs. 10,000 for Lok Sabha, Rs. 5,000 for Assembly), submit the affidavit, await scrutiny.\n\n4. Campaigning: Follow the Model Code of Conduct, do not use government resources, do not make inflammatory speeches, do not distribute liquor or gifts.\n\n5. Election expenditure limits: Lok Sabha Rs. 70 lakh, Assembly Rs. 28 lakh, Rajya Sabha Rs. 70 lakh.\n\n6. Important dates: Notification of election, last date for filing nomination, scrutiny of nomination papers, last date for withdrawal, date of polling, date of counting.\n\n7. If elected: Take oath of office, attend Parliament/Assembly sessions, represent the constituency, declare assets and liabilities."},

    {"section": "10", "title": "How to Get Legal Aid in India",
     "text": "Step-by-step guide to get legal aid in India:\n\n1. Eligibility: Women and children, persons with disabilities, members of Scheduled Castes and Scheduled Tribes, persons with annual income below Rs. 3 lakh, persons in custody, victims of human trafficking.\n\n2. Legal Services Authorities: National Legal Services Authority (NALSA), State Legal Services Authorities, District Legal Services Authorities, Taluk Legal Services Committees, High Court Legal Services Committees.\n\n3. Procedure: Visit the nearest Legal Services Authority, fill in the application form, submit with supporting documents, the Authority will verify eligibility and appoint a lawyer.\n\n4. Documents required: Application form, identity proof, income certificate, caste certificate (if applicable).\n\n5. Services provided: Free legal advice, free legal representation in courts, free legal aid in civil and criminal cases, family disputes, labour disputes, consumer disputes.\n\n6. Important points: Legal aid is a constitutional right, you cannot be denied legal aid if you are eligible, the lawyer will represent you free of charge.\n\n7. Helpline numbers: NALSA Helpline 15100, National Consumer Helpline 1800-11-4000, Women Helpline 181, Child Helpline 1098, Police Helpline 100."},
])

print("Done: practical-guides-4")
