#!/usr/bin/env python3
"""Upload Miscellaneous Acts to S3."""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from s3_upload import create_act

# ─── Contempt of Courts Act, 1971 ───
create_act("contempt-of-courts-act", "The Contempt of Courts Act, 1971", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Contempt of Courts Act, 1971. It extends to the whole of India. It shall come into force on such date as the Central Government may, by notification in the Official Gazette, appoint."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'contempt of court' means civil contempt or criminal contempt; (b) 'civil contempt' means wilful disobedience to any judgment, decree, direction, order, writ or other process of a court, or wilful breach of an undertaking given to a court; (c) 'criminal contempt' means the publication, whether by words, spoken or written, or by signs, or by visible representation, or otherwise, of any matter or doing any act which: (i) scandalises or tends to scandalise, or lowers or tends to lower the authority of, any court; or (ii) prejudices or interferes or tends to interfere with the due course of any judicial proceeding; or (iii) interferes or tends to interfere with, or obstructs or tends to obstruct, the administration of justice in any other manner; (d) 'High Court' means the High Court for a State and includes the High Court of Delhi and the High Court of Judicature at Bombay in respect of the Union Territory of Goa, Dadra and Nagar Haveli, and Daman and Diu; (e) 'judge' means a judge of a High Court or a court of session; (f) 'published' includes publication in print, broadcast, or electronic media."},
    {"section": "3", "title": "Innocent publication and distribution of matter not contempt",
     "text": "(1) No person shall be guilty of contempt of court for publishing any fair, accurate and timely report of any judicial proceeding, or for distributing or publishing any such report. (2) No person shall be guilty of contempt of court for publishing any matter: (a) which is contained in a judicial proceeding, unless the court has expressly prohibited the publication of such matter; or (b) which is contained in a judgment, decree or order of a court, or which is contained in any order made in chambers by a judge, unless the court has expressly prohibited the publication of such matter. (3) Nothing in this section shall be deemed to apply to the publication of any matter which is known by the person publishing it to be false."},
    {"section": "4", "title": "Fair and accurate report of judicial proceedings not contempt",
     "text": "No person shall be guilty of contempt of court for publishing a fair and accurate report of any judicial proceeding, or for distributing or publishing any such report."},
    {"section": "5", "title": "Publication of substance of judicial proceedings",
     "text": "No person shall be guilty of contempt of court for publishing the substance of any judicial proceeding, unless the court has expressly prohibited the publication of such substance."},
    {"section": "6", "title": "Fair criticism of judicial acts not contempt",
     "text": "No person shall be guilty of contempt of court for publishing any fair comment on the merits of any judicial act done by a court or judge in the discharge of his judicial duty, provided the comment does not amount to scandalising the court."},
    {"section": "7", "title": "Complaint against presiding officers of subordinate courts",
     "text": "Nothing in this Act shall be deemed to apply to any contempt which is alleged to have been committed by a person who publishes any matter concerning any subordinate court, if the matter published is a fair and accurate report of the proceedings of the court, or a fair comment on the merits of the case."},
    {"section": "8", "title": "Act not to apply to legislature",
     "text": "Nothing in this Act shall be deemed to apply to any person in respect of anything said or done by him in the Legislature of the Union or of a State, or any Committee thereof, or in any court when sitting in a legislative capacity."},
    {"section": "9", "title": "Power to punish contempt of court",
     "text": "(1) The Supreme Court and every High Court shall have the power to punish any person for contempt of court. (2) The High Court shall have the power to punish any person for contempt of any subordinate court. (3) The power to punish for contempt shall be exercised in accordance with the provisions of this Act."},
    {"section": "10", "title": "Criminal contempt",
     "text": "(1) Criminal contempt shall be punishable with simple imprisonment for a term which may extend to six months, or with fine which may extend to two thousand rupees, or with both. (2) No High Court shall take cognizance of a criminal contempt alleged to have been committed in respect of a subordinate court, unless the subordinate court certifies that the contempt is of such a nature that it interferes with or tends to interfere with, or obstructs or tends to obstruct, the administration of justice in the subordinate court."},
    {"section": "11", "title": "Civil contempt",
     "text": "(1) Civil contempt shall be punishable with simple imprisonment for a term which may extend to six months, or with fine which may extend to two thousand rupees, or with both. (2) No court shall take cognizance of a civil contempt on its own motion, unless the person aggrieved makes an application to the court."},
    {"section": "12", "title": "Sentences of imprisonment to run consecutively",
     "text": "Where a person is convicted of more than one contempt, the sentences of imprisonment shall run consecutively, unless the court otherwise orders."},
    {"section": "13", "title": "Contempt by judge",
     "text": "A judge shall not be liable for contempt of court in respect of anything done by him in the discharge of his judicial duty, unless the thing was done in bad faith or in a manner not warranted by law."},
    {"section": "14", "title": "Contempt in certain cases",
     "text": "A person shall not be guilty of contempt of court for publishing any matter concerning any court which is: (a) contained in a judicial proceeding; (b) contained in a judgment, decree or order of a court; (c) contained in any order made in chambers by a judge, provided the court has not expressly prohibited the publication of such matter."},
    {"section": "15", "title": "Procedure for punishment of contempt",
     "text": "(1) No court shall take cognizance of a contempt of court on its own motion, unless the matter is brought to its notice by the Advocate General or any person authorised by him, or by any person who is not the Advocate General but who has obtained the leave of the court to make the application. (2) The court shall issue a notice to the person alleged to be guilty of contempt. (3) The person shall have the right to appear in person or through a lawyer and to show cause why he should not be punished for contempt."},
    {"section": "16", "title": "Power of High Court to transfer contempt petitions",
     "text": "A High Court may transfer any contempt petition pending before it to another High Court, if it is of the opinion that the transfer is in the interests of justice."},
    {"section": "17", "title": "Application of certain sections of the Code of Criminal Procedure",
     "text": "The provisions of sections 340 to 348 of the Code of Criminal Procedure, 1973 shall apply to the trial of offences under this Act."},
    {"section": "18", "title": "Limitation",
     "text": "No court shall take cognizance of a contempt of court after the expiry of one year from the date on which the contempt was committed."},
    {"section": "19", "title": "Bar on courts",
     "text": "Nothing in this Act shall be construed as limiting the powers of the Supreme Court or any High Court to punish for contempt of court."},
    {"section": "20", "title": "Power to make rules",
     "text": "The Supreme Court and every High Court may make rules for carrying out the provisions of this Act. Such rules may provide for all matters which are required to be prescribed under this Act."},
])

# ─── Official Secrets Act, 1923 ───
create_act("official-secrets-act", "The Official Secrets Act, 1923", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Official Secrets Act, 1923. It extends to the whole of India. It came into force on the 1st day of October, 1923."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'code' includes any password, sign, design, signal, marking, or other method of secret identification; (b) 'document' includes any written, printed, or electronic record, map, plan, design, photograph, or any other material containing information; (c) 'official code' means any code, password, design, signal, marking, or other method of secret identification used for the purposes of the Government; (d) 'official secret' includes any information, document, or material which is classified as official secret under this Act; (e) 'password' includes any word, phrase, code, or number used for the purposes of secret identification; (f) 'prohibited place' means any place belonging to or occupied by the Government, or any place used for any secret official purpose, or any place which is notified as a prohibited place under this Act."},
    {"section": "3", "title": "Penalty for spying",
     "text": "(1) Any person who, for any purpose prejudicial to the safety or interests of the State: (a) approaches, inspects, passes over, or is in the neighbourhood of, or enters, any prohibited place; (b) makes any sketch, plan, model, or note which is calculated to be or might be or is intended to be, directly or indirectly, useful to an enemy; (c) obtains, collects, records, publishes, or communicates, or attempts to obtain, collect, record, publish, or communicate, any information, document, or material which is calculated to be or might be or is intended to be, directly or indirectly, useful to an enemy; (d) receives or possesses any information, document, or material which he knows or has reasonable ground to believe, has been obtained or disclosed in contravention of this Act, shall be punishable with imprisonment for a term which may extend to fourteen years, or with fine, or with both."},
    {"section": "4", "title": "Penalty for wrongful communication of official secrets",
     "text": "(1) Any person who, having in his possession or under his control any information, document, or material which he knows or has reasonable ground to believe is an official secret, communicates the same to any person in contravention of this Act, shall be punishable with imprisonment for a term which may extend to three years, or with fine, or with both. (2) The offence under this section shall be cognizable and non-bailable."},
    {"section": "5", "title": "Penalty for failure to protect official secrets",
     "text": "Any person who, being in possession of any information, document, or material which he knows or has reasonable ground to believe is an official secret, fails to take reasonable care to protect the same, or fails to comply with any direction of the Government for the protection of the same, shall be punishable with imprisonment for a term which may extend to two years, or with fine, or with both."},
    {"section": "6", "title": "Penalty for retention of official secrets",
     "text": "Any person who, having in his possession or under his control any information, document, or material which he knows or has reasonable ground to believe is an official secret, retains the same after he has ceased to be entitled to possess it, shall be punishable with imprisonment for a term which may extend to two years, or with fine, or with both."},
    {"section": "7", "title": "Penalty for disclosure of information by public servants",
     "text": "Any public servant who, in the course of his official duties, discloses any information, document, or material which he knows or has reasonable ground to believe is an official secret, to any person who is not authorised to receive the same, shall be punishable with imprisonment for a term which may extend to seven years, or with fine, or with both."},
    {"section": "8", "title": "Penalty for unauthorised possession of official secrets",
     "text": "Any person who, without lawful authority, possesses any information, document, or material which he knows or has reasonable ground to believe is an official secret, shall be punishable with imprisonment for a term which may extend to three years, or with fine, or with both."},
    {"section": "9", "title": "Penalty for contravention of orders relating to prohibited places",
     "text": "Any person who, in contravention of any order made under this Act, enters, approaches, or is in the neighbourhood of, any prohibited place, shall be punishable with imprisonment for a term which may extend to two years, or with fine, or with both."},
    {"section": "10", "title": "Penalty for falsification of documents",
     "text": "Any person who, for the purpose of committing or facilitating the commission of an offence under this Act, falsifies, alters, or destroys any document, shall be punishable with imprisonment for a term which may extend to seven years, or with fine, or with both."},
    {"section": "11", "title": "Penalty for abetment",
     "text": "Any person who abets, or attempts to commit, or abets the commission of, any offence under this Act, shall be punishable with the same punishment as is provided for the offence."},
    {"section": "12", "title": "Cognizance of offences",
     "text": "(1) No court shall take cognizance of any offence under this Act except on a complaint made by the Central Government or any officer authorised by it. (2) The offence shall be triable by a court of session."},
    {"section": "13", "title": "Protection of actions done in good faith",
     "text": "No suit, prosecution, or other legal proceeding shall lie against any person for anything done or intended to be done in good faith under this Act."},
    {"section": "14", "title": "Power to make rules",
     "text": "The Central Government may make rules for carrying out the purposes of this Act. Such rules may provide for all matters which are required to be prescribed under this Act."},
    {"section": "15", "title": "Power to declare places as prohibited places",
     "text": "The Central Government may, by notification in the Official Gazette, declare any place to be a prohibited place for the purposes of this Act."},
    {"section": "16", "title": "Continuance of certain provisions",
     "text": "The provisions of this Act shall be in addition to, and not in derogation of, the provisions of any other law for the time being in force."},
])

# ─── Passport Act, 1967 ───
create_act("passport-act", "The Passport Act, 1967", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Passport Act, 1967. It extends to the whole of India. It shall come into force on such date as the Central Government may, by notification in the Official Gazette, appoint."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'passport' means a passport issued or deemed to have been issued under this Act; (b) 'passport authority' means the Passport Authority or any authority designated by the Central Government for the issue of passports; (c) 'prescribed' means prescribed by rules made under this Act; (d) 'travel document' means any document for the travel of persons from or to India."},
    {"section": "3", "title": "Power to make rules",
     "text": "(1) The Central Government may make rules for the issue, renewal, and revocation of passports and travel documents. (2) The rules may prescribe the form and contents of passports, the fee payable, and the conditions for the issue of passports."},
    {"section": "4", "title": "Issue of passports",
     "text": "(1) The passport authority may, on an application made in the prescribed form, issue a passport to any citizen of India. (2) The passport authority may refuse to issue a passport if: (a) the applicant is not a citizen of India; (b) the applicant has furnished false information; (c) the applicant is likely to prejudice the sovereignty and integrity of India; (d) the applicant is likely to endanger the security of India; (e) the applicant has been convicted of a criminal offence; (f) the applicant has been detained under any law for the prevention of detention; (g) the applicant is subject to any order of a court prohibiting him from leaving India. (3) The passport authority may impose conditions on the issue of a passport."},
    {"section": "5", "title": "Renewal of passports",
     "text": "(1) The passport authority may, on an application made in the prescribed form, renew a passport. (2) The renewal shall be for a period of ten years from the date of issue. (3) The passport authority may refuse to renew a passport on any of the grounds mentioned in section 4."},
    {"section": "6", "title": "Revocation of passports",
     "text": "(1) The passport authority may revoke a passport if: (a) the passport was obtained by fraud or misrepresentation; (b) the passport holder has violated any condition of the passport; (c) the passport holder has been convicted of a criminal offence; (d) the passport holder is subject to any order of a court prohibiting him from leaving India; (e) the passport holder has ceased to be a citizen of India; (f) the passport holder is likely to prejudice the sovereignty and integrity of India; (g) the passport holder is likely to endanger the security of India. (2) The passport authority may, after giving the passport holder an opportunity of being heard, revoke the passport."},
    {"section": "7", "title": "Surrender of passports",
     "text": "The passport authority may require any person who holds a passport to surrender the passport if: (a) the passport has been revoked; (b) the passport has expired; (c) the passport holder has ceased to be a citizen of India; (d) the passport authority is satisfied that the passport is no longer required."},
    {"section": "8", "title": "Validity of passports",
     "text": "(1) A passport issued under this Act shall be valid for a period of ten years from the date of issue. (2) A passport may be renewed for a further period of ten years. (3) A passport shall cease to be valid if it is revoked, expired, or surrendered."},
    {"section": "9", "title": "Travel document",
     "text": "The Central Government may issue travel documents to persons who are not citizens of India, or to citizens of India who are not holders of passports, for the purpose of travel to and from India."},
    {"section": "10", "title": "Impounding of passports",
     "text": "(1) The passport authority may impound a passport if: (a) the passport was obtained by fraud or misrepresentation; (b) the passport holder has violated any condition of the passport; (c) the passport holder has been convicted of a criminal offence; (d) the passport holder is subject to any order of a court prohibiting him from leaving India. (2) The passport authority may, after giving the passport holder an opportunity of being heard, impound the passport."},
    {"section": "11", "title": "Refusal of passports",
     "text": "(1) The passport authority may refuse to issue a passport if: (a) the applicant is not a citizen of India; (b) the applicant has furnished false information; (c) the applicant is likely to prejudice the sovereignty and integrity of India; (d) the applicant is likely to endanger the security of India; (e) the applicant has been convicted of a criminal offence; (f) the applicant has been detained under any law for the prevention of detention; (g) the applicant is subject to any order of a court prohibiting him from leaving India. (2) The passport authority may, in its discretion, refuse to issue a passport without assigning any reason."},
    {"section": "12", "title": "Appeal against refusal or revocation",
     "text": "(1) Any person aggrieved by the refusal of the passport authority to issue, renew, or revive a passport, or by the revocation or impounding of a passport, may appeal to the prescribed authority. (2) The appeal shall be made within thirty days of the order. (3) The appeal shall be in the prescribed form and shall be accompanied by the prescribed fee. (4) The appeal authority may confirm, modify, or reverse the order of the passport authority."},
    {"section": "13", "title": "Offences",
     "text": "Any person who: (a) uses a passport which is not valid; (b) uses a passport which has been revoked; (c) uses a passport which has been impounded; (d) furnishes false information in an application for a passport; (e) is in possession of a passport which is not his, shall be punishable with imprisonment for a term which may extend to three years, or with fine, or with both."},
    {"section": "14", "title": "Cognizance of offences",
     "text": "No court shall take cognizance of any offence under this Act except on a complaint made by the passport authority or any officer authorised by it."},
    {"section": "15", "title": "Protection of actions taken in good faith",
     "text": "No suit, prosecution, or other legal proceeding shall lie against the Central Government or any officer of the Government for anything done or intended to be done in good faith under this Act."},
    {"section": "16", "title": "Power to make rules",
     "text": "The Central Government may make rules for carrying out the provisions of this Act. Such rules may provide for all matters which are required to be prescribed under this Act."},
])

# ─── Indian Telegraph Act, 1885 ───
create_act("indian-telegraph-act", "The Indian Telegraph Act, 1885", [
    {"section": "1", "title": "Short title and commencement",
     "text": "This Act may be called the Indian Telegraph Act, 1885. It extends to the whole of India. It came into force on the 1st day of October, 1885."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'message' means any communication sent by telegraph, or in any other form of electronic communication; (b) 'telegraph' means any apparatus, instrument, appliance, or contrivance used for the transmission of signs, signals, writing, images, sounds, or intelligence of any nature by wire, radio, or other means of communication; (c) 'telegraph authority' means any person authorised under this Act to establish, maintain, or work a telegraph; (d) 'telephone' means any apparatus, instrument, appliance, or contrivance used for the transmission of speech by wire or other means of communication."},
    {"section": "3", "title": "Government's exclusive privilege of establishing telegraphs",
     "text": "(1) Within India, the Central Government shall have the exclusive privilege of establishing, maintaining, and working telegraphs. (2) The Central Government may grant a licence to any person to establish, maintain, or work a telegraph within any part of India. (3) The Central Government may revoke any licence granted under this section."},
    {"section": "4", "title": "Power to grant licence",
     "text": "(1) The Central Government may, by licence, authorise any person to establish, maintain, and work a telegraph within any part of India. (2) The licence may be granted subject to such conditions and restrictions as the Central Government may think fit. (3) The Central Government may revoke any licence granted under this section."},
    {"section": "5", "title": "Power to take possession of licensed telegraphs",
     "text": "(1) Where the Central Government is of opinion that it is necessary for the defence of India or for the maintenance of public order, it may take possession of any licensed telegraph. (2) The Central Government may use the telegraph for any purpose it thinks fit. (3) The Central Government shall pay compensation for the use of the telegraph."},
    {"section": "6", "title": "Power to establish telegraphs on lands",
     "text": "(1) The telegraph authority may, for the purpose of establishing, maintaining, or working a telegraph, enter upon any land and erect any poles, wires, or other apparatus. (2) The telegraph authority may also dig up any land for the purpose of laying underground wires. (3) The telegraph authority shall pay compensation for any damage caused by the exercise of the powers under this section."},
    {"section": "7", "title": "Extraordinary powers of telegraph authority",
     "text": "The telegraph authority may, for the purpose of establishing, maintaining, or working a telegraph: (a) enter upon any land and erect any poles, wires, or other apparatus; (b) dig up any land; (c) fell or lop any tree; (d) remove any obstruction; (e) do any other thing which may be necessary for the purpose."},
    {"section": "8", "title": "Interruption of telegraphic communication",
     "text": "(1) Any person who, intentionally, and without authority, intercepts or interrupts any telegraphic communication, shall be punishable with imprisonment for a term which may extend to three years, or with fine, or with both. (2) The offence shall be cognizable and non-bailable."},
    {"section": "9", "title": "Telegraph officer divulging contents of messages",
     "text": "(1) Any telegraph officer who, without reasonable cause, divulges the contents of any message, or any part thereof, shall be punishable with imprisonment for a term which may extend to three years, or with fine, or with both. (2) The offence shall be cognizable and non-bailable."},
    {"section": "10", "title": "Telegraph officer disclosing information",
     "text": "(1) Any telegraph officer who, without reasonable cause, discloses any information relating to the working of a telegraph, shall be punishable with imprisonment for a term which may extend to one year, or with fine, or with both. (2) The offence shall be cognizable and non-bailable."},
    {"section": "11", "title": "Theft of telegraphic messages",
     "text": "(1) Any person who steals, or fraudulently takes, or removes any telegraphic message, or any part thereof, shall be punishable with imprisonment for a term which may extend to three years, or with fine, or with both. (2) The offence shall be cognizable and non-bailable."},
    {"section": "12", "title": "Fraudulent damage to telegraphs",
     "text": "(1) Any person who, intentionally and fraudulently, injures, removes, tampers with, or destroys any telegraph, or any part thereof, shall be punishable with imprisonment for a term which may extend to three years, or with fine, or with both. (2) The offence shall be cognizable and non-bailable."},
    {"section": "13", "title": "Negligent damage to telegraphs",
     "text": "(1) Any person who, negligently, injures, removes, tampers with, or destroys any telegraph, or any part thereof, shall be punishable with fine which may extend to one hundred rupees. (2) The offence shall be non-cognizable and bailable."},
    {"section": "14", "title": "Saving",
     "text": "Nothing in this Act shall be deemed to authorise any person to establish, maintain, or work a telegraph in contravention of any other law for the time being in force."},
    {"section": "15", "title": "Power to make rules",
     "text": "The Central Government may make rules for carrying out the purposes of this Act. Such rules may provide for all matters which are required to be prescribed under this Act."},
])

# ─── Census Act, 1948 ───
create_act("census-act", "The Census Act, 1948", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Census Act, 1948. It extends to the whole of India. It came into force on the 1st day of April, 1948."},
    {"section": "2", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'census' means the census of population taken under this Act; (b) 'census officer' means any person appointed to take or assist in taking the census under this Act; (c) 'census paper' means any form used for the collection of information at the census; (d) 'Director of Census Operations' means the officer appointed by the Central Government to direct the census operations in a State; (e) 'population' means the total number of persons living in a defined area at a given time."},
    {"section": "3", "title": "Power to take census",
     "text": "(1) The Central Government may, by notification in the Official Gazette, direct that a census of the population of India shall be taken. (2) The census shall be taken in such manner as may be prescribed. (3) The census shall be taken on such date or dates as may be appointed by the Central Government."},
    {"section": "4", "title": "Appointment of census officers",
     "text": "(1) The Director of Census Operations may, with the previous sanction of the Central Government, appoint any person to be a census officer. (2) Every census officer shall be given a certificate of appointment which he shall produce when required to do so. (3) A census officer may be removed from office by the Director of Census Operations."},
    {"section": "5", "title": "Duties of census officers",
     "text": "Every census officer shall: (a) take the census in the area assigned to him; (b) collect the information required by the census papers; (c) fill up the census papers in accordance with the information collected; (d) submit the census papers to the Director of Census Operations; (e) comply with any direction given to him by the Director of Census Operations."},
    {"section": "6", "title": "Obligation of persons to answer questions",
     "text": "(1) Every person who is a inhabitant of India shall be bound to answer truly all questions relating to the census which may be put to him by a census officer. (2) The refusal to answer, or the giving of false answers, shall be punishable with fine which may extend to one hundred rupees. (3) No person shall be required to answer any question which may incriminate him."},
    {"section": "7", "title": "Entry of dwellings",
     "text": "A census officer may, after giving due notice, enter any dwelling house or premises for the purpose of taking the census. He may also require any person in the dwelling house or premises to give him such information as may be necessary for the census."},
    {"section": "8", "title": "Census papers",
     "text": "(1) The census papers shall be in such form as may be prescribed. (2) The census papers shall contain such information as may be prescribed. (3) The census papers shall be filled up by the census officer in accordance with the information collected."},
    {"section": "9", "title": "Custody of census papers",
     "text": "(1) The census papers shall be in the custody of the Director of Census Operations. (2) The Director of Census Operations may take such steps as may be necessary for the preservation of the census papers. (3) The census papers shall not be produced in any court of law except with the previous sanction of the Central Government."},
    {"section": "10", "title": "Penalty for neglect, refusal or false answers",
     "text": "Any person who: (a) refuses to answer truly any question put to him by a census officer; (b) gives false answers to any question put to him by a census officer; (c) obstructs any census officer in the discharge of his duties; (d) mutilates, destroys, or removes any census paper, shall be punishable with fine which may extend to one hundred rupees."},
    {"section": "11", "title": "Penalty for false statements",
     "text": "Any person who, in any census paper, makes any statement which is false in any material particular, shall be punishable with fine which may extend to five hundred rupees."},
    {"section": "12", "title": "Penalty for fraud",
     "text": "Any person who, for the purpose of committing or facilitating the commission of any fraud in connection with the census, makes any false statement, or falsifies any census paper, shall be punishable with imprisonment for a term which may extend to six months, or with fine, or with both."},
    {"section": "13", "title": "Protection of information",
     "text": "(1) All information collected at the census shall be treated as confidential. (2) No information collected at the census shall be used for the purpose of identification of any individual. (3) No information collected at the census shall be disclosed to any person except with the previous sanction of the Central Government. (4) The information may be used for statistical purposes only."},
    {"section": "14", "title": "Publication of results",
     "text": "(1) The Central Government may publish the results of the census. (2) The results may be published in such form and manner as the Central Government may think fit. (3) The results shall not contain any information which may identify any individual."},
    {"section": "15", "title": "Powers of Central Government",
     "text": "(1) The Central Government may make rules for carrying out the purposes of this Act. (2) Such rules may provide for all matters which are required to be prescribed under this Act. (3) The rules shall be laid before each House of Parliament."},
])

# ─── Epidemic Diseases Act, 1897 ───
create_act("epidemic-diseases-act", "The Epidemic Diseases Act, 1897", [
    {"section": "1", "title": "Short title, extent and commencement",
     "text": "This Act may be called the Epidemic Diseases Act, 1897. It extends to the whole of India. It came into force on the 4th day of February, 1897."},
    {"section": "2", "title": "Power to take special measures and prescribe regulations as to dangerous epidemic disease",
     "text": "(1) When at any time the State Government is satisfied that the State or any part thereof is threatened with an outbreak of any dangerous epidemic disease, the State Government may, if it thinks that the ordinary provisions of the law for the time being in force for the prevention of the spread of the disease are insufficient for the purpose, take, or require or empower any person to take, such measures and, by public notice, prescribe such temporary regulations to be observed by the public or by any person or class of persons as it shall deem necessary to prevent the outbreak of such disease or the spread thereof. (2) The State Government may direct the closure of any public place, school, college, or any other institution, or may prohibit any gathering of persons. (3) The State Government may also prescribe regulations for the quarantine of persons affected or suspected to be affected by the disease. (4) The State Government may also prescribe regulations for the disinfection of any premises, vehicle, or other thing."},
    {"section": "3", "title": "Penalty for disobeying regulations",
     "text": "(1) Any person who disobeys any regulation or order made under section 2 shall be punishable with imprisonment for a term which may extend to six months, or with fine, or with both. (2) The offence shall be cognizable and bailable. (3) Any person who disobeys any direction given under section 2 shall be punishable with imprisonment for a term which may extend to one year, or with fine, or with both."},
    {"section": "4", "title": "Protection to persons acting under this Act",
     "text": "No suit, prosecution, or other legal proceeding shall lie against any person for anything done or intended to be done in good faith under this Act."},
    {"section": "5", "title": "Power of Central Government",
     "text": "(1) The Central Government may, if it considers that the outbreak of any dangerous epidemic disease in any State or group of States is of such a nature as to affect or is likely to affect the public health in India or any part thereof, take such measures as it may consider necessary. (2) The Central Government may issue directions to the State Governments for the prevention of the spread of the disease. (3) The Central Government may also make rules for carrying out the purposes of this Act."},
    {"section": "5A", "title": "Power to add to or amend schedule",
     "text": "The Central Government may, by notification in the Official Gazette, add to or amend the schedule to this Act. The schedule shall list the diseases to which this Act applies."},
    {"section": "5B", "title": "Penalty for obstruction",
     "text": "Any person who, without any reasonable cause, obstructs any person acting under the authority of the State Government or the Central Government in the discharge of his duties under this Act shall be punishable with imprisonment for a term which may extend to six months, or with fine, or with both."},
    {"section": "6", "title": "Application of Act",
     "text": "This Act shall apply to the whole of India, and to all Indian citizens and to any person on board any ship or aircraft registered in India."},
    {"section": "7", "title": "Repeal",
     "text": "The Epidemic Diseases Act, 1897 is repealed by the Epidemic Diseases (Amendment) Act, 2020. The amended Act provides for enhanced penalties and more comprehensive measures for the prevention of epidemic diseases."},
    {"section": "8", "title": "Definitions",
     "text": "In this Act, unless the context otherwise requires: (a) 'dangerous epidemic disease' means any disease which is declared as a dangerous epidemic disease by the Central Government or the State Government; (b) 'State Government' means the Government of a State; (c) 'Central Government' means the Government of India."},
    {"section": "9", "title": "Power to make rules",
     "text": "The Central Government and the State Government may make rules for carrying out the purposes of this Act. Such rules may provide for all matters which are required to be prescribed under this Act."},
    {"section": "10", "title": "Protection of property",
     "text": "The State Government may take such measures as may be necessary for the protection of property from damage or destruction during an epidemic. The State Government may also prescribe compensation for any property damaged or destroyed."},
    {"section": "11", "title": "Medical examination and treatment",
     "text": "The State Government may require any person who is affected or suspected to be affected by a dangerous epidemic disease to submit to medical examination and treatment. The State Government may also prescribe the manner of medical examination and treatment."},
    {"section": "12", "title": "Quarantine",
     "text": "The State Government may quarantine any person who is affected or suspected to be affected by a dangerous epidemic disease. The quarantine may be for such period as may be necessary for the prevention of the spread of the disease."},
])

print("Done: contempt-of-courts-act, official-secrets-act, passport-act, indian-telegraph-act, census-act, epidemic-diseases-act")
