#!/usr/bin/env python3
"""Create missing criminal & special security acts for S3 KB."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from s3_upload import create_act

ACTS = [
    {
        "id": "arms-act",
        "title": "Arms Act, 1959",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Arms Act, 1959. It extends to the whole of India and came into force on 1st October 1962."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) ammunition includes bombs, grenades, rockets, torpedoes, mines and other explosives; (b) fire-arm means any gun, rifle, carbine, revolver, pistol, air-gun or any weapon designed to discharge a projectile involving force of explosion or combustion; (c) prohibited arm means any fire-arm specified in Schedule I; (d) weapon includes fire-arms and ammunition."},
            {"section": "3", "title": "Prohibition of acquisition or possession without licence",
             "text": "No person shall acquire, have in his possession, or carry any fire-arm or ammunition unless he holds a licence granted under this Act. Violation is punishable with imprisonment up to 3 years, or fine up to Rs 5,000, or both. For prohibited arms, imprisonment may extend to 7 years."},
            {"section": "4", "title": "Licence for acquisition and possession",
             "text": "Any person desiring to acquire or possess any fire-arm or ammunition may apply to the licensing authority. The authority considers nature of past offences, experience in use of arms, reasons for acquisition, and other relevant factors before granting or refusing licence."},
            {"section": "5", "title": "Licence for manufacture, sale, etc.",
             "text": "No person shall manufacture, sell, transfer, convert, repair, test or proof any fire-arm or ammunition unless he holds a licence granted under this Act. The licensing authority may grant licence subject to prescribed conditions."},
            {"section": "7", "title": "Government may prohibit or restrict transfer",
             "text": "The Central Government may prohibit, wholly or partially, the transfer by sale, gift, bequest, exchange or otherwise of any fire-arm or ammunition specified in Schedule I by order published in the Official Gazette."},
            {"section": "17", "title": "Penalty for possession without licence",
             "text": "Whoever acquires, possesses or carries any fire-arm or ammunition in contravention of section 3 shall be punished with imprisonment up to 3 years, or fine up to Rs 5,000, or both. If committed with a prohibited arm, imprisonment may extend to 7 years."},
            {"section": "18", "title": "Penalty for manufacture, sale without licence",
             "text": "Whoever manufactures, sells, transfers, converts, repairs, tests or proofs any fire-arm or ammunition without licence shall be punished with imprisonment up to 7 years, or fine, or both."},
            {"section": "19", "title": "Penalty for contravention of licence conditions",
             "text": "Whoever possesses fire-arm or ammunition in contravention of any condition of a licence shall be punished with imprisonment up to 3 years, or fine up to Rs 5,000, or both."},
            {"section": "24", "title": "Power to cancel licence",
             "text": "The licensing authority may cancel or revoke any licence if satisfied that the holder is unfit, or licence was obtained by fraud, or conditions have been contravened."},
            {"section": "25", "title": "Power to seize and forfeit",
             "text": "Any police officer or authorised officer may seize fire-arm or ammunition in respect of which an offence under this Act is suspected. Seized items shall be forfeited to the Central Government."},
            {"section": "27", "title": "Protection of action taken in good faith",
             "text": "No suit, prosecution or legal proceeding shall lie against the Government or any officer for anything done in good faith under this Act."},
        ]
    },
    {
        "id": "dowry-prohibition-act",
        "title": "Dowry Prohibition Act, 1961",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Dowry Prohibition Act, 1961. It extends to the whole of India. Came into force on 1st May 1961."},
            {"section": "2", "title": "Definition of dowry",
             "text": "Dowry means any property or valuable security given or agreed to be given either directly or indirectly by one party to a marriage to the other party, or by the parent of either party or by any other person, to either party or to any other person, at or before or any time after the marriage in connection with the marriage."},
            {"section": "3", "title": "Penalty for giving or taking dowry",
             "text": "If any person gives or takes or abets the giving or taking of dowry, he shall be punished with imprisonment not less than 5 years and fine not less than Rs 15,000 or the value of such dowry, whichever is more. The Court may impose lesser sentence for adequate and special reasons."},
            {"section": "4", "title": "Penalty for demanding dowry",
             "text": "If any person demands, directly or indirectly, any dowry from the parents or guardian of a bride or bridegroom, he shall be punished with imprisonment not less than 5 years and fine not less than Rs 15,000."},
            {"section": "4A", "title": "Ban on advertisement for dowry",
             "text": "No person shall publish any advertisement offering or asking for dowry in any media including electronic media. Punishment: imprisonment up to 6 months, or fine up to Rs 5,000, or both."},
            {"section": "5", "title": "Agreement for dowry to be void",
             "text": "Any agreement for the giving or taking of dowry shall be void. No court shall enforce any such agreement whether made before or after commencement of this Act."},
            {"section": "6", "title": "Gifts at marriage",
             "text": "This Act does not apply to gifts given at the time of marriage to the bride or bridegroom without any demand for dowry, provided such gifts are entered in a list maintained in accordance with prescribed rules."},
            {"section": "7", "title": "Cognizance of offence",
             "text": "No court inferior to a Metropolitan Magistrate or Judicial Magistrate First Class shall try offences under this Act. Cognizance may be taken upon complaint by the aggrieved person, a relative, a Government officer, or any person who has made a written complaint to the police."},
            {"section": "8A", "title": "Burden of proof",
             "text": "Where any person is prosecuted for giving, taking, or demanding dowry, the burden of proving that he had not given, taken, or demanded the dowry shall be on him."},
        ]
    },
    {
        "id": "uapa-act",
        "title": "Unlawful Activities (Prevention) Act, 1967",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Unlawful Activities (Prevention) Act, 1967. It extends to the whole of India and to Indian citizens outside India."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) unlawful activity means any action intended to bring about question of secession, or which challenges sovereignty of India, or causes disaffection against India; (b) terrorist act means any act with intent to threaten unity, integrity, security or sovereignty of India or to strike terror in people; (c) terrorist organisation means an organisation listed in the Schedule or declared under this Act."},
            {"section": "3", "title": "Power to declare unlawful associations",
             "text": "Where the Central Government is of opinion that any association is or has become unlawful, it may declare the association to be unlawful by order published in the Official Gazette."},
            {"section": "4", "title": "Effect of declaration",
             "text": "Once an association is declared unlawful: (a) every member punishable with imprisonment up to 2 years; (b) association shall be dissolved; (c) funds and assets seized and forfeited to the Central Government."},
            {"section": "9", "title": "Penalty for membership of unlawful association",
             "text": "Whoever is a member of an unlawful association shall be punished with imprisonment up to 2 years, or fine, or both."},
            {"section": "13", "title": "Punishment for unlawful activities",
             "text": "Whoever takes part in, commits, undertakes, abets, or assists unlawful activities shall be punished with imprisonment up to 7 years, or fine, or both."},
            {"section": "15", "title": "Terrorist act",
             "text": "Whoever does any act with intent to threaten or likely to threaten unity, integrity, security or sovereignty of India, or with intent to strike terror, shall be punished with imprisonment not less than 5 years which may extend to life imprisonment, and shall also be liable to fine."},
            {"section": "16", "title": "Punishment for conspiracy relating to terrorist act",
             "text": "Whoever conspires, attempts, advocates, abets or encourages commission of a terrorist act shall be punished with imprisonment not less than 5 years which may extend to life, and shall also be liable to fine."},
            {"section": "17", "title": "Punishment for raising funds for terrorist act",
             "text": "Whoever raises funds for committing any terrorist act or to further activities of any terrorist organisation shall be punished with imprisonment not less than 5 years which may extend to life, and shall also be liable to fine."},
            {"section": "20", "title": "Membership of terrorist organisation",
             "text": "Whoever is or continues to be a member of a terrorist organisation shall be punished with imprisonment not less than 5 years which may extend to life, and shall also be liable to fine."},
            {"section": "22", "title": "Power to search and seize",
             "text": "A police officer not below rank of Superintendent of Police may search any person and seize property or money being used for purposes of a terrorist organisation."},
            {"section": "24", "title": "Attachment and forfeiture of property",
             "text": "The court may order attachment and forfeiture of property derived from terrorist acts or held by a terrorist organisation."},
        ]
    },
    {
        "id": "pmla-act",
        "title": "Prevention of Money Laundering Act, 2002",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Prevention of Money Laundering Act, 2002. Extends to whole of India. Came into force on 1st July 2005."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) proceeds of crime means any property derived or obtained directly or indirectly as a result of criminal activity relating to a scheduled offence; (b) scheduled offence means an offence specified in the Schedule; (c) money laundering has the meaning in section 3."},
            {"section": "3", "title": "Offence of money laundering",
             "text": "Whosoever directly or indirectly attempts to indulge, or knowingly assists or is party to any process or activity connected with proceeds of crime including concealment, possession, acquisition, use and projecting it as untainted property, shall be guilty of money laundering."},
            {"section": "4", "title": "Punishment for money laundering",
             "text": "Rigorous imprisonment not less than 3 years which may extend to 7 years, and shall also be liable to fine. Where proceeds relate to NDPS Act offences, imprisonment not less than 10 years which may extend to life."},
            {"section": "5", "title": "Attachment of property",
             "text": "The Director or authorised officer may attach property involved in money laundering, including proceeds of crime or property used in commission of money laundering, by order in writing."},
            {"section": "8", "title": "Adjudicating Authority",
             "text": "The Central Government shall constitute an Adjudicating Authority for confirming attachment or confiscation of property under this Act. It shall consist of a Chairperson and two members."},
            {"section": "10", "title": "Special Courts",
             "text": "The Central Government shall designate one or more Courts of Session as Special Courts for trial of offences punishable under this Act, in consultation with the Chief Justice of the High Court."},
            {"section": "17", "title": "Power to search and seize",
             "text": "Any officer of the Enforcement Directorate not below rank of Assistant Director may search any person, place or thing and seize records, documents, cash, valuables or other property."},
            {"section": "19", "title": "Power to arrest",
             "text": "The Director or authorised officer may arrest any person whom he has reason to believe has been guilty of an offence under this Act. The arrested person must be informed of grounds and produced before Special Court within 24 hours."},
            {"section": "24", "title": "Special Court to try offences",
             "text": "The Special Court shall try offences under this Act and shall have all powers of a Court of Session under the Code of Criminal Procedure, 1973."},
            {"section": "44", "title": "Offence cognizable and non-bailable",
             "text": "The offence of money laundering shall be cognizable and non-bailable. CrPC provisions apply for arrest, bail and trial."},
            {"section": "50", "title": "Burden of proof",
             "text": "In proceedings under this Act, the burden of proving that any property is not the proceeds of crime shall be on the person claiming the same. The Special Court may presume that property is proceeds of crime based on materials placed before it."},
        ]
    },
    {
        "id": "explosive-substances-act",
        "title": "Explosive Substances Act, 1908",
        "sections": [
            {"section": "1", "title": "Short title and extent",
             "text": "This Act may be called the Explosive Substances Act, 1908. It extends to the whole of India."},
            {"section": "2", "title": "Definitions",
             "text": "Explosive substance includes any material or substance which is likely to cause an explosion, or any dangerous explosive substance within the meaning of section 4 of the Indian Explosives Act, 1884."},
            {"section": "3", "title": "Penalty for making or possessing explosive substance under suspicious circumstances",
             "text": "Any person who makes or knowingly has in his possession or under his control any explosive substance, under such circumstances as to give rise to a reasonable suspicion that he is not making or does not have it in his possession for a lawful object, shall be punished with imprisonment which may extend to 14 years, or fine, or both."},
            {"section": "4", "title": "Penalty for making or possession of explosive for commissioning offence",
             "text": "Any person who makes or knowingly has in his possession or under his control any explosive substance, intending or knowing it to be likely that it will be used for committing an offence punishable under this Act, shall be punished with imprisonment which may extend to life, or imprisonment up to 10 years, and fine."},
            {"section": "5", "title": "Penalty for making or possession of explosive for purposes of terrorism",
             "text": "Any person who makes or has in his possession any explosive substance with intent to commit or to aid in the commission of an act of terrorism shall be punished with imprisonment for life, or imprisonment up to 10 years, and fine."},
            {"section": "6", "title": "Penalty for knowingly harbouring persons in possession of explosive",
             "text": "Any person who knowingly harbours or conceals or shelters any person whom he knows or has reason to believe to have in his possession any explosive substance in contravention of this Act shall be punished with imprisonment up to 10 years, or fine, or both."},
            {"section": "7", "title": "Penalty for criminal breach of trust in respect of explosive",
             "text": "Any person who, being entrusted with any explosive substance, criminal breach of trust in respect thereof shall be punished with imprisonment for life, or imprisonment up to 14 years, and fine."},
            {"section": "8", "title": "Power to search and seize",
             "text": "Any police officer may search any place and seize any explosive substance found therein which he has reason to believe is being used or intended to be used for any unlawful purpose."},
        ]
    },
    {
        "id": "prevention-of-corruption-amended-act",
        "title": "Prevention of Corruption Act, 1988 (Amended 2018)",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Prevention of Corruption Act, 1988. It extends to the whole of India. Amended by the Prevention of Corruption (Amendment) Act, 2018."},
            {"section": "2", "title": "Definitions",
             "text": "Key definitions: (a) public servant means any person specified in section 21 of the Indian Penal Code; (b) gratification includes any gift, money, donation, reward or other pecuniary advantage; (c) valuable thing includes any movable or immovable property, service, favour or advantage."},
            {"section": "7", "title": "Taking gratification by public servant as reward for official act",
             "text": "Any public servant who obtains any valuable thing without consideration from any person as a reward for doing or forbearing to do any official act shall be punished with imprisonment not less than 3 years but which may extend to 7 years, and shall also be liable to fine."},
            {"section": "8", "title": "Taking gratification for exercise of personal influence with public servant",
             "text": "Any public servant who obtains any valuable thing without consideration from any person for exercising personal influence with another public servant shall be punished with imprisonment up to 3 years, or fine, or both."},
            {"section": "9", "title": "Public servant obtaining any valuable thing without consideration from person concerned in proceeding",
             "text": "Any public servant who obtains any valuable thing without consideration from any person concerned in any proceeding pending in such public servant's court or office shall be punished with imprisonment not less than 3 years but which may extend to 7 years, and fine."},
            {"section": "10", "title": "Punishment for abetment of offences",
             "text": "Whoever abets any offence under this Act shall be punished with imprisonment for a term which may extend to the punishment provided for the offence abetted."},
            {"section": "11", "title": "Public servant habitually engaging in corrupt practices",
             "text": "Any public servant who habitually accepts or obtains or attempts to obtain any gratification from any person for performing or not performing any official act shall be punished with imprisonment not less than 3 years but which may extend to 7 years, and fine."},
            {"section": "13", "title": "Criminal misconduct by public servant",
             "text": "Any public servant commits criminal misconduct if he: (a) habitually accepts gratification other than his legal remuneration; or (b) dishonestly or fraudulently misappropriates or converts for his own use any property entrusted to him or under his control as a public servant; or (c) enriches himself by any illegal means in the discharge of his official duties. Punishment: imprisonment not less than 3 years but which may extend to 7 years, and fine."},
            {"section": "14", "title": "Punishment for criminal misconduct",
             "text": "Whoever commits criminal misconduct shall be punished with imprisonment not less than 3 years which may extend to 7 years, and shall also be liable to fine. If the public servant is found to have committed criminal misconduct in relation to any decision or action which has resulted in loss to the exchequer, the imprisonment shall not be less than 5 years."},
            {"section": "15", "title": "Verification of assets by public servants",
             "text": "Every public servant shall, on appointment, submit an annual statement of assets and liabilities of himself and his family members. Failure to submit or making false statements is an offence under this Act."},
            {"section": "17", "title": "Cognizance of offence",
             "text": "No court shall take cognizance of an offence under this Act except upon a complaint made by: (a) the Central Government or State Government; or (b) a person authorised by the Central Government or State Government; or (c) a complainant who has been given prior sanction of the Government."},
            {"section": "19", "title": "Previous sanction of government",
             "text": "No court shall take cognizance of an offence alleged to have been committed by a public servant except with the previous sanction of: (a) the Central Government in case of a central government servant; (b) the State Government in case of a state government servant."},
        ]
    },
    {
        "id": "armed-forces-special-powers-act",
        "title": "Armed Forces (Special Powers) Act, 1958",
        "sections": [
            {"section": "1", "title": "Short title, extent and commencement",
             "text": "This Act may be called the Armed Forces (Special Powers) Act, 1958. Originally extended to the 7 North-Eastern States; now applicable to disturbed areas across India including Jammu & Kashmir (as AFSPA, 1990)."},
            {"section": "2", "title": "Definitions",
             "text": "In this Act: (a) armed forces means the military forces of the Union operating as land forces; (b) distubed area means any area declared as such under section 3; (c) military officer means any commissioned or gazetted officer in the armed forces."},
            {"section": "3", "title": "Power to declare disturbed area",
             "text": "If the Central Government or the Governor of a State is of opinion that the whole or any part of a State or Union Territory is in such a disturbed or dangerous condition that the use of armed forces in aid of civil power is necessary, the Government may declare the whole or any part of the area as a disturbed area."},
            {"section": "4", "title": "Special powers of armed forces in disturbed areas",
             "text": "In a disturbed area, any commissioned officer, warrant officer or junior commissioned officer of the armed forces may: (a) fire upon or otherwise use force against any person who is acting in contravention of any law or order; (b) arrest without warrant any person who has committed or is about to commit a cognizable offence; (c) enter and search any premises without warrant to make arrests or recover persons, arms, explosives or ammunition."},
            {"section": "4A", "title": "Protection of persons acting under this Act",
             "text": "No prosecution, suit or other legal proceeding shall be instituted against any person in respect of anything done or purported to be done in exercise of powers conferred by this Act, except with the previous sanction of the Central Government."},
            {"section": "5", "title": "Power to prohibit assembly of five or more persons",
             "text": "In a disturbed area, the District Magistrate or any other officer authorised by the Central Government may prohibit the assembly of five or more persons, and any person violating such prohibition shall be punishable with imprisonment up to 1 year, or fine, or both."},
            {"section": "6", "title": "Arrest without warrant",
             "text": "Any person arrested under this Act shall be made over to the officer in charge of the nearest police station with all reasonable despatch, and a report of the arrest shall be made to the District Magistrate within 48 hours."},
        ]
    },
]

if __name__ == "__main__":
    print("Creating criminal & special security acts...")
    for act in ACTS:
        create_act(act["id"], act["title"], act["sections"])
    print(f"Done: {len(ACTS)} acts created.")
